# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from nlp_drone_control/Plan.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import nlp_drone_control.msg

class Plan(genpy.Message):
  _md5sum = "6b2a4346febb21fc1800dd9e94fdf8ca"
  _type = "nlp_drone_control/Plan"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# Represents a list of tool calls (a full execution plan)
nlp_drone_control/ToolCall[] tool_calls
uint8 replan_mode          # 0 = APPEND, 1 = REPLACE


================================================================================
MSG: nlp_drone_control/ToolCall
# Represents a single tool call produced by the LLM
string function_name       # e.g. "takeoff"
string arguments_json      # raw JSON string of arguments

"""
  __slots__ = ['tool_calls','replan_mode']
  _slot_types = ['nlp_drone_control/ToolCall[]','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       tool_calls,replan_mode

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Plan, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.tool_calls is None:
        self.tool_calls = []
      if self.replan_mode is None:
        self.replan_mode = 0
    else:
      self.tool_calls = []
      self.replan_mode = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.tool_calls)
      buff.write(_struct_I.pack(length))
      for val1 in self.tool_calls:
        _x = val1.function_name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1.arguments_json
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.replan_mode
      buff.write(_get_struct_B().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.tool_calls is None:
        self.tool_calls = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.tool_calls = []
      for i in range(0, length):
        val1 = nlp_drone_control.msg.ToolCall()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.function_name = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.function_name = str[start:end]
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.arguments_json = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.arguments_json = str[start:end]
        self.tool_calls.append(val1)
      start = end
      end += 1
      (self.replan_mode,) = _get_struct_B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.tool_calls)
      buff.write(_struct_I.pack(length))
      for val1 in self.tool_calls:
        _x = val1.function_name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1.arguments_json
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.replan_mode
      buff.write(_get_struct_B().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.tool_calls is None:
        self.tool_calls = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.tool_calls = []
      for i in range(0, length):
        val1 = nlp_drone_control.msg.ToolCall()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.function_name = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.function_name = str[start:end]
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.arguments_json = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.arguments_json = str[start:end]
        self.tool_calls.append(val1)
      start = end
      end += 1
      (self.replan_mode,) = _get_struct_B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
