// Generated by gencpp from file fleet_manager/DroneStatus.msg
// DO NOT EDIT!


#ifndef FLEET_MANAGER_MESSAGE_DRONESTATUS_H
#define FLEET_MANAGER_MESSAGE_DRONESTATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace fleet_manager
{
template <class ContainerAllocator>
struct DroneStatus_
{
  typedef DroneStatus_<ContainerAllocator> Type;

  DroneStatus_()
    : drone_id()
    , status(0)
    , last_completed_task_index(0)
    , last_known_pose()  {
    }
  DroneStatus_(const ContainerAllocator& _alloc)
    : drone_id(_alloc)
    , status(0)
    , last_completed_task_index(0)
    , last_known_pose(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _drone_id_type;
  _drone_id_type drone_id;

   typedef uint8_t _status_type;
  _status_type status;

   typedef int32_t _last_completed_task_index_type;
  _last_completed_task_index_type last_completed_task_index;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _last_known_pose_type;
  _last_known_pose_type last_known_pose;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(UNKNOWN)
  #undef UNKNOWN
#endif
#if defined(_WIN32) && defined(ACTIVE)
  #undef ACTIVE
#endif
#if defined(_WIN32) && defined(NEEDS_BACKUP)
  #undef NEEDS_BACKUP
#endif
#if defined(_WIN32) && defined(OFFLINE)
  #undef OFFLINE
#endif

  enum {
    UNKNOWN = 0u,
    ACTIVE = 1u,
    NEEDS_BACKUP = 2u,
    OFFLINE = 3u,
  };


  typedef boost::shared_ptr< ::fleet_manager::DroneStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fleet_manager::DroneStatus_<ContainerAllocator> const> ConstPtr;

}; // struct DroneStatus_

typedef ::fleet_manager::DroneStatus_<std::allocator<void> > DroneStatus;

typedef boost::shared_ptr< ::fleet_manager::DroneStatus > DroneStatusPtr;
typedef boost::shared_ptr< ::fleet_manager::DroneStatus const> DroneStatusConstPtr;

// constants requiring out of line definition

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fleet_manager::DroneStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fleet_manager::DroneStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fleet_manager::DroneStatus_<ContainerAllocator1> & lhs, const ::fleet_manager::DroneStatus_<ContainerAllocator2> & rhs)
{
  return lhs.drone_id == rhs.drone_id &&
    lhs.status == rhs.status &&
    lhs.last_completed_task_index == rhs.last_completed_task_index &&
    lhs.last_known_pose == rhs.last_known_pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fleet_manager::DroneStatus_<ContainerAllocator1> & lhs, const ::fleet_manager::DroneStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fleet_manager

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::fleet_manager::DroneStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fleet_manager::DroneStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fleet_manager::DroneStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fleet_manager::DroneStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fleet_manager::DroneStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fleet_manager::DroneStatus_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fleet_manager::DroneStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4399a33682bd42bcbd894637e74a998e";
  }

  static const char* value(const ::fleet_manager::DroneStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4399a33682bd42bcULL;
  static const uint64_t static_value2 = 0xbd894637e74a998eULL;
};

template<class ContainerAllocator>
struct DataType< ::fleet_manager::DroneStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fleet_manager/DroneStatus";
  }

  static const char* value(const ::fleet_manager::DroneStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fleet_manager::DroneStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# [修改] 在消息定义中添加常量\n"
"# Drone Status Constants\n"
"uint8 UNKNOWN=0\n"
"uint8 ACTIVE=1\n"
"uint8 NEEDS_BACKUP=2\n"
"uint8 OFFLINE=3\n"
"\n"
"# Message Fields\n"
"string drone_id\n"
"uint8 status\n"
"int32 last_completed_task_index\n"
"geometry_msgs/Pose last_known_pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::fleet_manager::DroneStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fleet_manager::DroneStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.drone_id);
      stream.next(m.status);
      stream.next(m.last_completed_task_index);
      stream.next(m.last_known_pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DroneStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fleet_manager::DroneStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fleet_manager::DroneStatus_<ContainerAllocator>& v)
  {
    s << indent << "drone_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.drone_id);
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
    s << indent << "last_completed_task_index: ";
    Printer<int32_t>::stream(s, indent + "  ", v.last_completed_task_index);
    s << indent << "last_known_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.last_known_pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FLEET_MANAGER_MESSAGE_DRONESTATUS_H
