// Generated by gencpp from file fleet_manager/InjectTasksResponse.msg
// DO NOT EDIT!


#ifndef FLEET_MANAGER_MESSAGE_INJECTTASKSRESPONSE_H
#define FLEET_MANAGER_MESSAGE_INJECTTASKSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace fleet_manager
{
template <class ContainerAllocator>
struct InjectTasksResponse_
{
  typedef InjectTasksResponse_<ContainerAllocator> Type;

  InjectTasksResponse_()
    : success(false)  {
    }
  InjectTasksResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::fleet_manager::InjectTasksResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fleet_manager::InjectTasksResponse_<ContainerAllocator> const> ConstPtr;

}; // struct InjectTasksResponse_

typedef ::fleet_manager::InjectTasksResponse_<std::allocator<void> > InjectTasksResponse;

typedef boost::shared_ptr< ::fleet_manager::InjectTasksResponse > InjectTasksResponsePtr;
typedef boost::shared_ptr< ::fleet_manager::InjectTasksResponse const> InjectTasksResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fleet_manager::InjectTasksResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fleet_manager::InjectTasksResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fleet_manager::InjectTasksResponse_<ContainerAllocator1> & lhs, const ::fleet_manager::InjectTasksResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fleet_manager::InjectTasksResponse_<ContainerAllocator1> & lhs, const ::fleet_manager::InjectTasksResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fleet_manager

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::fleet_manager::InjectTasksResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fleet_manager::InjectTasksResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fleet_manager::InjectTasksResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fleet_manager::InjectTasksResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fleet_manager::InjectTasksResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fleet_manager::InjectTasksResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fleet_manager::InjectTasksResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::fleet_manager::InjectTasksResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::fleet_manager::InjectTasksResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fleet_manager/InjectTasksResponse";
  }

  static const char* value(const ::fleet_manager::InjectTasksResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fleet_manager::InjectTasksResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"\n"
;
  }

  static const char* value(const ::fleet_manager::InjectTasksResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fleet_manager::InjectTasksResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct InjectTasksResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fleet_manager::InjectTasksResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fleet_manager::InjectTasksResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FLEET_MANAGER_MESSAGE_INJECTTASKSRESPONSE_H
