// Generated by gencpp from file fleet_manager/InjectTasksRequest.msg
// DO NOT EDIT!


#ifndef FLEET_MANAGER_MESSAGE_INJECTTASKSREQUEST_H
#define FLEET_MANAGER_MESSAGE_INJECTTASKSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <fleet_manager/TaskStatus.h>

namespace fleet_manager
{
template <class ContainerAllocator>
struct InjectTasksRequest_
{
  typedef InjectTasksRequest_<ContainerAllocator> Type;

  InjectTasksRequest_()
    : tasks()
    , assign_to_drone_id()  {
    }
  InjectTasksRequest_(const ContainerAllocator& _alloc)
    : tasks(_alloc)
    , assign_to_drone_id(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::fleet_manager::TaskStatus_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::fleet_manager::TaskStatus_<ContainerAllocator> >::other >  _tasks_type;
  _tasks_type tasks;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _assign_to_drone_id_type;
  _assign_to_drone_id_type assign_to_drone_id;





  typedef boost::shared_ptr< ::fleet_manager::InjectTasksRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fleet_manager::InjectTasksRequest_<ContainerAllocator> const> ConstPtr;

}; // struct InjectTasksRequest_

typedef ::fleet_manager::InjectTasksRequest_<std::allocator<void> > InjectTasksRequest;

typedef boost::shared_ptr< ::fleet_manager::InjectTasksRequest > InjectTasksRequestPtr;
typedef boost::shared_ptr< ::fleet_manager::InjectTasksRequest const> InjectTasksRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fleet_manager::InjectTasksRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fleet_manager::InjectTasksRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fleet_manager::InjectTasksRequest_<ContainerAllocator1> & lhs, const ::fleet_manager::InjectTasksRequest_<ContainerAllocator2> & rhs)
{
  return lhs.tasks == rhs.tasks &&
    lhs.assign_to_drone_id == rhs.assign_to_drone_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fleet_manager::InjectTasksRequest_<ContainerAllocator1> & lhs, const ::fleet_manager::InjectTasksRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fleet_manager

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::fleet_manager::InjectTasksRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fleet_manager::InjectTasksRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fleet_manager::InjectTasksRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fleet_manager::InjectTasksRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fleet_manager::InjectTasksRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fleet_manager::InjectTasksRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fleet_manager::InjectTasksRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a336e44c7ab89d7dbd3e266b33615a37";
  }

  static const char* value(const ::fleet_manager::InjectTasksRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa336e44c7ab89d7dULL;
  static const uint64_t static_value2 = 0xbd3e266b33615a37ULL;
};

template<class ContainerAllocator>
struct DataType< ::fleet_manager::InjectTasksRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fleet_manager/InjectTasksRequest";
  }

  static const char* value(const ::fleet_manager::InjectTasksRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fleet_manager::InjectTasksRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fleet_manager/TaskStatus[] tasks\n"
"string assign_to_drone_id\n"
"\n"
"================================================================================\n"
"MSG: fleet_manager/TaskStatus\n"
"# [修改] 在消息定义中添加常量\n"
"# Task Status Constants\n"
"uint8 PENDING=0\n"
"uint8 IN_PROGRESS=1\n"
"uint8 COMPLETED=2\n"
"uint8 NEEDS_BACKUP=3 # 注意：我把FAILED改成了NEEDS_BACKUP以匹配你的C++代码\n"
"\n"
"# Message Fields\n"
"int32 task_id\n"
"nlp_drone_control/Action action_details\n"
"uint8 status\n"
"string assigned_drone_id\n"
"\n"
"================================================================================\n"
"MSG: nlp_drone_control/Action\n"
"# Represents a single tool call produced by the LLM\n"
"string function_name       # e.g. \"takeoff\"\n"
"string arguments_json      # raw JSON string of arguments\n"
"\n"
;
  }

  static const char* value(const ::fleet_manager::InjectTasksRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fleet_manager::InjectTasksRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.tasks);
      stream.next(m.assign_to_drone_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct InjectTasksRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fleet_manager::InjectTasksRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fleet_manager::InjectTasksRequest_<ContainerAllocator>& v)
  {
    s << indent << "tasks[]" << std::endl;
    for (size_t i = 0; i < v.tasks.size(); ++i)
    {
      s << indent << "  tasks[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::fleet_manager::TaskStatus_<ContainerAllocator> >::stream(s, indent + "    ", v.tasks[i]);
    }
    s << indent << "assign_to_drone_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.assign_to_drone_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FLEET_MANAGER_MESSAGE_INJECTTASKSREQUEST_H
