// Generated by gencpp from file fleet_manager/InjectTasks.msg
// DO NOT EDIT!


#ifndef FLEET_MANAGER_MESSAGE_INJECTTASKS_H
#define FLEET_MANAGER_MESSAGE_INJECTTASKS_H

#include <ros/service_traits.h>


#include <fleet_manager/InjectTasksRequest.h>
#include <fleet_manager/InjectTasksResponse.h>


namespace fleet_manager
{

struct InjectTasks
{

typedef InjectTasksRequest Request;
typedef InjectTasksResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct InjectTasks
} // namespace fleet_manager


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::fleet_manager::InjectTasks > {
  static const char* value()
  {
    return "72ac7b4be33eb67b134d27e55502c210";
  }

  static const char* value(const ::fleet_manager::InjectTasks&) { return value(); }
};

template<>
struct DataType< ::fleet_manager::InjectTasks > {
  static const char* value()
  {
    return "fleet_manager/InjectTasks";
  }

  static const char* value(const ::fleet_manager::InjectTasks&) { return value(); }
};


// service_traits::MD5Sum< ::fleet_manager::InjectTasksRequest> should match
// service_traits::MD5Sum< ::fleet_manager::InjectTasks >
template<>
struct MD5Sum< ::fleet_manager::InjectTasksRequest>
{
  static const char* value()
  {
    return MD5Sum< ::fleet_manager::InjectTasks >::value();
  }
  static const char* value(const ::fleet_manager::InjectTasksRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::fleet_manager::InjectTasksRequest> should match
// service_traits::DataType< ::fleet_manager::InjectTasks >
template<>
struct DataType< ::fleet_manager::InjectTasksRequest>
{
  static const char* value()
  {
    return DataType< ::fleet_manager::InjectTasks >::value();
  }
  static const char* value(const ::fleet_manager::InjectTasksRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::fleet_manager::InjectTasksResponse> should match
// service_traits::MD5Sum< ::fleet_manager::InjectTasks >
template<>
struct MD5Sum< ::fleet_manager::InjectTasksResponse>
{
  static const char* value()
  {
    return MD5Sum< ::fleet_manager::InjectTasks >::value();
  }
  static const char* value(const ::fleet_manager::InjectTasksResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::fleet_manager::InjectTasksResponse> should match
// service_traits::DataType< ::fleet_manager::InjectTasks >
template<>
struct DataType< ::fleet_manager::InjectTasksResponse>
{
  static const char* value()
  {
    return DataType< ::fleet_manager::InjectTasks >::value();
  }
  static const char* value(const ::fleet_manager::InjectTasksResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FLEET_MANAGER_MESSAGE_INJECTTASKS_H
