// Generated by gencpp from file fleet_manager/QueryFleetAndTasksRequest.msg
// DO NOT EDIT!


#ifndef FLEET_MANAGER_MESSAGE_QUERYFLEETANDTASKSREQUEST_H
#define FLEET_MANAGER_MESSAGE_QUERYFLEETANDTASKSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace fleet_manager
{
template <class ContainerAllocator>
struct QueryFleetAndTasksRequest_
{
  typedef QueryFleetAndTasksRequest_<ContainerAllocator> Type;

  QueryFleetAndTasksRequest_()
    {
    }
  QueryFleetAndTasksRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::fleet_manager::QueryFleetAndTasksRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fleet_manager::QueryFleetAndTasksRequest_<ContainerAllocator> const> ConstPtr;

}; // struct QueryFleetAndTasksRequest_

typedef ::fleet_manager::QueryFleetAndTasksRequest_<std::allocator<void> > QueryFleetAndTasksRequest;

typedef boost::shared_ptr< ::fleet_manager::QueryFleetAndTasksRequest > QueryFleetAndTasksRequestPtr;
typedef boost::shared_ptr< ::fleet_manager::QueryFleetAndTasksRequest const> QueryFleetAndTasksRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fleet_manager::QueryFleetAndTasksRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fleet_manager::QueryFleetAndTasksRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace fleet_manager

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::fleet_manager::QueryFleetAndTasksRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fleet_manager::QueryFleetAndTasksRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fleet_manager::QueryFleetAndTasksRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fleet_manager::QueryFleetAndTasksRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fleet_manager::QueryFleetAndTasksRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fleet_manager::QueryFleetAndTasksRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fleet_manager::QueryFleetAndTasksRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::fleet_manager::QueryFleetAndTasksRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::fleet_manager::QueryFleetAndTasksRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fleet_manager/QueryFleetAndTasksRequest";
  }

  static const char* value(const ::fleet_manager::QueryFleetAndTasksRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fleet_manager::QueryFleetAndTasksRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 请求部分为空\n"
;
  }

  static const char* value(const ::fleet_manager::QueryFleetAndTasksRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fleet_manager::QueryFleetAndTasksRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct QueryFleetAndTasksRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fleet_manager::QueryFleetAndTasksRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::fleet_manager::QueryFleetAndTasksRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // FLEET_MANAGER_MESSAGE_QUERYFLEETANDTASKSREQUEST_H
