// Generated by gencpp from file fleet_manager/QueryFleetAndTasksResponse.msg
// DO NOT EDIT!


#ifndef FLEET_MANAGER_MESSAGE_QUERYFLEETANDTASKSRESPONSE_H
#define FLEET_MANAGER_MESSAGE_QUERYFLEETANDTASKSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <fleet_manager/DroneStatus.h>
#include <fleet_manager/TaskStatus.h>

namespace fleet_manager
{
template <class ContainerAllocator>
struct QueryFleetAndTasksResponse_
{
  typedef QueryFleetAndTasksResponse_<ContainerAllocator> Type;

  QueryFleetAndTasksResponse_()
    : drones()
    , tasks()  {
    }
  QueryFleetAndTasksResponse_(const ContainerAllocator& _alloc)
    : drones(_alloc)
    , tasks(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::fleet_manager::DroneStatus_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::fleet_manager::DroneStatus_<ContainerAllocator> >::other >  _drones_type;
  _drones_type drones;

   typedef std::vector< ::fleet_manager::TaskStatus_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::fleet_manager::TaskStatus_<ContainerAllocator> >::other >  _tasks_type;
  _tasks_type tasks;





  typedef boost::shared_ptr< ::fleet_manager::QueryFleetAndTasksResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fleet_manager::QueryFleetAndTasksResponse_<ContainerAllocator> const> ConstPtr;

}; // struct QueryFleetAndTasksResponse_

typedef ::fleet_manager::QueryFleetAndTasksResponse_<std::allocator<void> > QueryFleetAndTasksResponse;

typedef boost::shared_ptr< ::fleet_manager::QueryFleetAndTasksResponse > QueryFleetAndTasksResponsePtr;
typedef boost::shared_ptr< ::fleet_manager::QueryFleetAndTasksResponse const> QueryFleetAndTasksResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fleet_manager::QueryFleetAndTasksResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fleet_manager::QueryFleetAndTasksResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fleet_manager::QueryFleetAndTasksResponse_<ContainerAllocator1> & lhs, const ::fleet_manager::QueryFleetAndTasksResponse_<ContainerAllocator2> & rhs)
{
  return lhs.drones == rhs.drones &&
    lhs.tasks == rhs.tasks;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fleet_manager::QueryFleetAndTasksResponse_<ContainerAllocator1> & lhs, const ::fleet_manager::QueryFleetAndTasksResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fleet_manager

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::fleet_manager::QueryFleetAndTasksResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fleet_manager::QueryFleetAndTasksResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fleet_manager::QueryFleetAndTasksResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fleet_manager::QueryFleetAndTasksResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fleet_manager::QueryFleetAndTasksResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fleet_manager::QueryFleetAndTasksResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fleet_manager::QueryFleetAndTasksResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a9cee634e5450b9a2e85c18da8e84744";
  }

  static const char* value(const ::fleet_manager::QueryFleetAndTasksResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa9cee634e5450b9aULL;
  static const uint64_t static_value2 = 0x2e85c18da8e84744ULL;
};

template<class ContainerAllocator>
struct DataType< ::fleet_manager::QueryFleetAndTasksResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fleet_manager/QueryFleetAndTasksResponse";
  }

  static const char* value(const ::fleet_manager::QueryFleetAndTasksResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fleet_manager::QueryFleetAndTasksResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 响应部分\n"
"fleet_manager/DroneStatus[] drones\n"
"fleet_manager/TaskStatus[] tasks\n"
"\n"
"\n"
"================================================================================\n"
"MSG: fleet_manager/DroneStatus\n"
"# [修改] 在消息定义中添加常量\n"
"# Drone Status Constants\n"
"uint8 UNKNOWN=0\n"
"uint8 ACTIVE=1\n"
"uint8 NEEDS_BACKUP=2\n"
"uint8 OFFLINE=3\n"
"\n"
"# Message Fields\n"
"string drone_id\n"
"uint8 status\n"
"int32 last_completed_task_index\n"
"geometry_msgs/Pose last_known_pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: fleet_manager/TaskStatus\n"
"# [修改] 在消息定义中添加常量\n"
"# Task Status Constants\n"
"uint8 PENDING=0\n"
"uint8 IN_PROGRESS=1\n"
"uint8 COMPLETED=2\n"
"uint8 NEEDS_BACKUP=3 # 注意：我把FAILED改成了NEEDS_BACKUP以匹配你的C++代码\n"
"\n"
"# Message Fields\n"
"int32 task_id\n"
"nlp_drone_control/Action action_details\n"
"uint8 status\n"
"string assigned_drone_id\n"
"\n"
"================================================================================\n"
"MSG: nlp_drone_control/Action\n"
"# Represents a single tool call produced by the LLM\n"
"string function_name       # e.g. \"takeoff\"\n"
"string arguments_json      # raw JSON string of arguments\n"
"\n"
;
  }

  static const char* value(const ::fleet_manager::QueryFleetAndTasksResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fleet_manager::QueryFleetAndTasksResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.drones);
      stream.next(m.tasks);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct QueryFleetAndTasksResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fleet_manager::QueryFleetAndTasksResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fleet_manager::QueryFleetAndTasksResponse_<ContainerAllocator>& v)
  {
    s << indent << "drones[]" << std::endl;
    for (size_t i = 0; i < v.drones.size(); ++i)
    {
      s << indent << "  drones[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::fleet_manager::DroneStatus_<ContainerAllocator> >::stream(s, indent + "    ", v.drones[i]);
    }
    s << indent << "tasks[]" << std::endl;
    for (size_t i = 0; i < v.tasks.size(); ++i)
    {
      s << indent << "  tasks[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::fleet_manager::TaskStatus_<ContainerAllocator> >::stream(s, indent + "    ", v.tasks[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // FLEET_MANAGER_MESSAGE_QUERYFLEETANDTASKSRESPONSE_H
