// Generated by gencpp from file fleet_manager/QueryFleetAndTasks.msg
// DO NOT EDIT!


#ifndef FLEET_MANAGER_MESSAGE_QUERYFLEETANDTASKS_H
#define FLEET_MANAGER_MESSAGE_QUERYFLEETANDTASKS_H

#include <ros/service_traits.h>


#include <fleet_manager/QueryFleetAndTasksRequest.h>
#include <fleet_manager/QueryFleetAndTasksResponse.h>


namespace fleet_manager
{

struct QueryFleetAndTasks
{

typedef QueryFleetAndTasksRequest Request;
typedef QueryFleetAndTasksResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct QueryFleetAndTasks
} // namespace fleet_manager


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::fleet_manager::QueryFleetAndTasks > {
  static const char* value()
  {
    return "a9cee634e5450b9a2e85c18da8e84744";
  }

  static const char* value(const ::fleet_manager::QueryFleetAndTasks&) { return value(); }
};

template<>
struct DataType< ::fleet_manager::QueryFleetAndTasks > {
  static const char* value()
  {
    return "fleet_manager/QueryFleetAndTasks";
  }

  static const char* value(const ::fleet_manager::QueryFleetAndTasks&) { return value(); }
};


// service_traits::MD5Sum< ::fleet_manager::QueryFleetAndTasksRequest> should match
// service_traits::MD5Sum< ::fleet_manager::QueryFleetAndTasks >
template<>
struct MD5Sum< ::fleet_manager::QueryFleetAndTasksRequest>
{
  static const char* value()
  {
    return MD5Sum< ::fleet_manager::QueryFleetAndTasks >::value();
  }
  static const char* value(const ::fleet_manager::QueryFleetAndTasksRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::fleet_manager::QueryFleetAndTasksRequest> should match
// service_traits::DataType< ::fleet_manager::QueryFleetAndTasks >
template<>
struct DataType< ::fleet_manager::QueryFleetAndTasksRequest>
{
  static const char* value()
  {
    return DataType< ::fleet_manager::QueryFleetAndTasks >::value();
  }
  static const char* value(const ::fleet_manager::QueryFleetAndTasksRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::fleet_manager::QueryFleetAndTasksResponse> should match
// service_traits::MD5Sum< ::fleet_manager::QueryFleetAndTasks >
template<>
struct MD5Sum< ::fleet_manager::QueryFleetAndTasksResponse>
{
  static const char* value()
  {
    return MD5Sum< ::fleet_manager::QueryFleetAndTasks >::value();
  }
  static const char* value(const ::fleet_manager::QueryFleetAndTasksResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::fleet_manager::QueryFleetAndTasksResponse> should match
// service_traits::DataType< ::fleet_manager::QueryFleetAndTasks >
template<>
struct DataType< ::fleet_manager::QueryFleetAndTasksResponse>
{
  static const char* value()
  {
    return DataType< ::fleet_manager::QueryFleetAndTasks >::value();
  }
  static const char* value(const ::fleet_manager::QueryFleetAndTasksResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FLEET_MANAGER_MESSAGE_QUERYFLEETANDTASKS_H
