// Generated by gencpp from file fleet_manager/TaskStatus.msg
// DO NOT EDIT!


#ifndef FLEET_MANAGER_MESSAGE_TASKSTATUS_H
#define FLEET_MANAGER_MESSAGE_TASKSTATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <nlp_drone_control/Action.h>

namespace fleet_manager
{
template <class ContainerAllocator>
struct TaskStatus_
{
  typedef TaskStatus_<ContainerAllocator> Type;

  TaskStatus_()
    : task_id(0)
    , action_details()
    , status(0)
    , assigned_drone_id()  {
    }
  TaskStatus_(const ContainerAllocator& _alloc)
    : task_id(0)
    , action_details(_alloc)
    , status(0)
    , assigned_drone_id(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _task_id_type;
  _task_id_type task_id;

   typedef  ::nlp_drone_control::Action_<ContainerAllocator>  _action_details_type;
  _action_details_type action_details;

   typedef uint8_t _status_type;
  _status_type status;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _assigned_drone_id_type;
  _assigned_drone_id_type assigned_drone_id;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(PENDING)
  #undef PENDING
#endif
#if defined(_WIN32) && defined(IN_PROGRESS)
  #undef IN_PROGRESS
#endif
#if defined(_WIN32) && defined(COMPLETED)
  #undef COMPLETED
#endif
#if defined(_WIN32) && defined(NEEDS_BACKUP)
  #undef NEEDS_BACKUP
#endif

  enum {
    PENDING = 0u,
    IN_PROGRESS = 1u,
    COMPLETED = 2u,
    NEEDS_BACKUP = 3u,
  };


  typedef boost::shared_ptr< ::fleet_manager::TaskStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fleet_manager::TaskStatus_<ContainerAllocator> const> ConstPtr;

}; // struct TaskStatus_

typedef ::fleet_manager::TaskStatus_<std::allocator<void> > TaskStatus;

typedef boost::shared_ptr< ::fleet_manager::TaskStatus > TaskStatusPtr;
typedef boost::shared_ptr< ::fleet_manager::TaskStatus const> TaskStatusConstPtr;

// constants requiring out of line definition

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fleet_manager::TaskStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fleet_manager::TaskStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fleet_manager::TaskStatus_<ContainerAllocator1> & lhs, const ::fleet_manager::TaskStatus_<ContainerAllocator2> & rhs)
{
  return lhs.task_id == rhs.task_id &&
    lhs.action_details == rhs.action_details &&
    lhs.status == rhs.status &&
    lhs.assigned_drone_id == rhs.assigned_drone_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fleet_manager::TaskStatus_<ContainerAllocator1> & lhs, const ::fleet_manager::TaskStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fleet_manager

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::fleet_manager::TaskStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fleet_manager::TaskStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fleet_manager::TaskStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fleet_manager::TaskStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fleet_manager::TaskStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fleet_manager::TaskStatus_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fleet_manager::TaskStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1a83d6845a55cd58a28f4d61df9680e1";
  }

  static const char* value(const ::fleet_manager::TaskStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1a83d6845a55cd58ULL;
  static const uint64_t static_value2 = 0xa28f4d61df9680e1ULL;
};

template<class ContainerAllocator>
struct DataType< ::fleet_manager::TaskStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fleet_manager/TaskStatus";
  }

  static const char* value(const ::fleet_manager::TaskStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fleet_manager::TaskStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# [修改] 在消息定义中添加常量\n"
"# Task Status Constants\n"
"uint8 PENDING=0\n"
"uint8 IN_PROGRESS=1\n"
"uint8 COMPLETED=2\n"
"uint8 NEEDS_BACKUP=3 # 注意：我把FAILED改成了NEEDS_BACKUP以匹配你的C++代码\n"
"\n"
"# Message Fields\n"
"int32 task_id\n"
"nlp_drone_control/Action action_details\n"
"uint8 status\n"
"string assigned_drone_id\n"
"\n"
"================================================================================\n"
"MSG: nlp_drone_control/Action\n"
"# Represents a single tool call produced by the LLM\n"
"string function_name       # e.g. \"takeoff\"\n"
"string arguments_json      # raw JSON string of arguments\n"
"\n"
;
  }

  static const char* value(const ::fleet_manager::TaskStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fleet_manager::TaskStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.task_id);
      stream.next(m.action_details);
      stream.next(m.status);
      stream.next(m.assigned_drone_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TaskStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fleet_manager::TaskStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fleet_manager::TaskStatus_<ContainerAllocator>& v)
  {
    s << indent << "task_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.task_id);
    s << indent << "action_details: ";
    s << std::endl;
    Printer< ::nlp_drone_control::Action_<ContainerAllocator> >::stream(s, indent + "  ", v.action_details);
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
    s << indent << "assigned_drone_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.assigned_drone_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FLEET_MANAGER_MESSAGE_TASKSTATUS_H
