// Generated by gencpp from file poi_state_server/GetPOIInfoRequest.msg
// DO NOT EDIT!


#ifndef POI_STATE_SERVER_MESSAGE_GETPOIINFOREQUEST_H
#define POI_STATE_SERVER_MESSAGE_GETPOIINFOREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace poi_state_server
{
template <class ContainerAllocator>
struct GetPOIInfoRequest_
{
  typedef GetPOIInfoRequest_<ContainerAllocator> Type;

  GetPOIInfoRequest_()
    : name()  {
    }
  GetPOIInfoRequest_(const ContainerAllocator& _alloc)
    : name(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;





  typedef boost::shared_ptr< ::poi_state_server::GetPOIInfoRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::poi_state_server::GetPOIInfoRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetPOIInfoRequest_

typedef ::poi_state_server::GetPOIInfoRequest_<std::allocator<void> > GetPOIInfoRequest;

typedef boost::shared_ptr< ::poi_state_server::GetPOIInfoRequest > GetPOIInfoRequestPtr;
typedef boost::shared_ptr< ::poi_state_server::GetPOIInfoRequest const> GetPOIInfoRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::poi_state_server::GetPOIInfoRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::poi_state_server::GetPOIInfoRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::poi_state_server::GetPOIInfoRequest_<ContainerAllocator1> & lhs, const ::poi_state_server::GetPOIInfoRequest_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::poi_state_server::GetPOIInfoRequest_<ContainerAllocator1> & lhs, const ::poi_state_server::GetPOIInfoRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace poi_state_server

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::poi_state_server::GetPOIInfoRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::poi_state_server::GetPOIInfoRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::poi_state_server::GetPOIInfoRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::poi_state_server::GetPOIInfoRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::poi_state_server::GetPOIInfoRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::poi_state_server::GetPOIInfoRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::poi_state_server::GetPOIInfoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c1f3d28f1b044c871e6eff2e9fc3c667";
  }

  static const char* value(const ::poi_state_server::GetPOIInfoRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc1f3d28f1b044c87ULL;
  static const uint64_t static_value2 = 0x1e6eff2e9fc3c667ULL;
};

template<class ContainerAllocator>
struct DataType< ::poi_state_server::GetPOIInfoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "poi_state_server/GetPOIInfoRequest";
  }

  static const char* value(const ::poi_state_server::GetPOIInfoRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::poi_state_server::GetPOIInfoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n"
;
  }

  static const char* value(const ::poi_state_server::GetPOIInfoRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::poi_state_server::GetPOIInfoRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetPOIInfoRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::poi_state_server::GetPOIInfoRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::poi_state_server::GetPOIInfoRequest_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // POI_STATE_SERVER_MESSAGE_GETPOIINFOREQUEST_H
