// Generated by gencpp from file poi_state_server/GetPOIInfoResponse.msg
// DO NOT EDIT!


#ifndef POI_STATE_SERVER_MESSAGE_GETPOIINFORESPONSE_H
#define POI_STATE_SERVER_MESSAGE_GETPOIINFORESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <poi_state_server/POIInfo.h>

namespace poi_state_server
{
template <class ContainerAllocator>
struct GetPOIInfoResponse_
{
  typedef GetPOIInfoResponse_<ContainerAllocator> Type;

  GetPOIInfoResponse_()
    : success(false)
    , message()
    , info()  {
    }
  GetPOIInfoResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , message(_alloc)
    , info(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  _message_type message;

   typedef  ::poi_state_server::POIInfo_<ContainerAllocator>  _info_type;
  _info_type info;





  typedef boost::shared_ptr< ::poi_state_server::GetPOIInfoResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::poi_state_server::GetPOIInfoResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetPOIInfoResponse_

typedef ::poi_state_server::GetPOIInfoResponse_<std::allocator<void> > GetPOIInfoResponse;

typedef boost::shared_ptr< ::poi_state_server::GetPOIInfoResponse > GetPOIInfoResponsePtr;
typedef boost::shared_ptr< ::poi_state_server::GetPOIInfoResponse const> GetPOIInfoResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::poi_state_server::GetPOIInfoResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::poi_state_server::GetPOIInfoResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::poi_state_server::GetPOIInfoResponse_<ContainerAllocator1> & lhs, const ::poi_state_server::GetPOIInfoResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.message == rhs.message &&
    lhs.info == rhs.info;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::poi_state_server::GetPOIInfoResponse_<ContainerAllocator1> & lhs, const ::poi_state_server::GetPOIInfoResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace poi_state_server

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::poi_state_server::GetPOIInfoResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::poi_state_server::GetPOIInfoResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::poi_state_server::GetPOIInfoResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::poi_state_server::GetPOIInfoResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::poi_state_server::GetPOIInfoResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::poi_state_server::GetPOIInfoResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::poi_state_server::GetPOIInfoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3031818a24a520f7e1e33482c6311280";
  }

  static const char* value(const ::poi_state_server::GetPOIInfoResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3031818a24a520f7ULL;
  static const uint64_t static_value2 = 0xe1e33482c6311280ULL;
};

template<class ContainerAllocator>
struct DataType< ::poi_state_server::GetPOIInfoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "poi_state_server/GetPOIInfoResponse";
  }

  static const char* value(const ::poi_state_server::GetPOIInfoResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::poi_state_server::GetPOIInfoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"string message\n"
"poi_state_server/POIInfo info\n"
"\n"
"\n"
"\n"
"================================================================================\n"
"MSG: poi_state_server/POIInfo\n"
"# POIInfo.msg\n"
"string name\n"
"string type\n"
"string description\n"
"geometry_msgs/Point position\n"
"poi_state_server/NamedPoint[] candidate_points\n"
"geometry_msgs/Point boundary_min\n"
"geometry_msgs/Point boundary_max\n"
"bool has_boundary\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: poi_state_server/NamedPoint\n"
"string name\n"
"geometry_msgs/Point point\n"
"\n"
;
  }

  static const char* value(const ::poi_state_server::GetPOIInfoResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::poi_state_server::GetPOIInfoResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.message);
      stream.next(m.info);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetPOIInfoResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::poi_state_server::GetPOIInfoResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::poi_state_server::GetPOIInfoResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.message);
    s << indent << "info: ";
    s << std::endl;
    Printer< ::poi_state_server::POIInfo_<ContainerAllocator> >::stream(s, indent + "  ", v.info);
  }
};

} // namespace message_operations
} // namespace ros

#endif // POI_STATE_SERVER_MESSAGE_GETPOIINFORESPONSE_H
