// Generated by gencpp from file poi_state_server/GetPOIInfo.msg
// DO NOT EDIT!


#ifndef POI_STATE_SERVER_MESSAGE_GETPOIINFO_H
#define POI_STATE_SERVER_MESSAGE_GETPOIINFO_H

#include <ros/service_traits.h>


#include <poi_state_server/GetPOIInfoRequest.h>
#include <poi_state_server/GetPOIInfoResponse.h>


namespace poi_state_server
{

struct GetPOIInfo
{

typedef GetPOIInfoRequest Request;
typedef GetPOIInfoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetPOIInfo
} // namespace poi_state_server


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::poi_state_server::GetPOIInfo > {
  static const char* value()
  {
    return "c65c76ed817470389da7b2cfd1cdfbea";
  }

  static const char* value(const ::poi_state_server::GetPOIInfo&) { return value(); }
};

template<>
struct DataType< ::poi_state_server::GetPOIInfo > {
  static const char* value()
  {
    return "poi_state_server/GetPOIInfo";
  }

  static const char* value(const ::poi_state_server::GetPOIInfo&) { return value(); }
};


// service_traits::MD5Sum< ::poi_state_server::GetPOIInfoRequest> should match
// service_traits::MD5Sum< ::poi_state_server::GetPOIInfo >
template<>
struct MD5Sum< ::poi_state_server::GetPOIInfoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::poi_state_server::GetPOIInfo >::value();
  }
  static const char* value(const ::poi_state_server::GetPOIInfoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::poi_state_server::GetPOIInfoRequest> should match
// service_traits::DataType< ::poi_state_server::GetPOIInfo >
template<>
struct DataType< ::poi_state_server::GetPOIInfoRequest>
{
  static const char* value()
  {
    return DataType< ::poi_state_server::GetPOIInfo >::value();
  }
  static const char* value(const ::poi_state_server::GetPOIInfoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::poi_state_server::GetPOIInfoResponse> should match
// service_traits::MD5Sum< ::poi_state_server::GetPOIInfo >
template<>
struct MD5Sum< ::poi_state_server::GetPOIInfoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::poi_state_server::GetPOIInfo >::value();
  }
  static const char* value(const ::poi_state_server::GetPOIInfoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::poi_state_server::GetPOIInfoResponse> should match
// service_traits::DataType< ::poi_state_server::GetPOIInfo >
template<>
struct DataType< ::poi_state_server::GetPOIInfoResponse>
{
  static const char* value()
  {
    return DataType< ::poi_state_server::GetPOIInfo >::value();
  }
  static const char* value(const ::poi_state_server::GetPOIInfoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // POI_STATE_SERVER_MESSAGE_GETPOIINFO_H
