// Generated by gencpp from file poi_state_server/ListPOIsResponse.msg
// DO NOT EDIT!


#ifndef POI_STATE_SERVER_MESSAGE_LISTPOISRESPONSE_H
#define POI_STATE_SERVER_MESSAGE_LISTPOISRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <poi_state_server/POIInfo.h>

namespace poi_state_server
{
template <class ContainerAllocator>
struct ListPOIsResponse_
{
  typedef ListPOIsResponse_<ContainerAllocator> Type;

  ListPOIsResponse_()
    : success(false)
    , message()
    , pois()  {
    }
  ListPOIsResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , message(_alloc)
    , pois(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  _message_type message;

   typedef std::vector< ::poi_state_server::POIInfo_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::poi_state_server::POIInfo_<ContainerAllocator> >::other >  _pois_type;
  _pois_type pois;





  typedef boost::shared_ptr< ::poi_state_server::ListPOIsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::poi_state_server::ListPOIsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ListPOIsResponse_

typedef ::poi_state_server::ListPOIsResponse_<std::allocator<void> > ListPOIsResponse;

typedef boost::shared_ptr< ::poi_state_server::ListPOIsResponse > ListPOIsResponsePtr;
typedef boost::shared_ptr< ::poi_state_server::ListPOIsResponse const> ListPOIsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::poi_state_server::ListPOIsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::poi_state_server::ListPOIsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::poi_state_server::ListPOIsResponse_<ContainerAllocator1> & lhs, const ::poi_state_server::ListPOIsResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.message == rhs.message &&
    lhs.pois == rhs.pois;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::poi_state_server::ListPOIsResponse_<ContainerAllocator1> & lhs, const ::poi_state_server::ListPOIsResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace poi_state_server

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::poi_state_server::ListPOIsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::poi_state_server::ListPOIsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::poi_state_server::ListPOIsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::poi_state_server::ListPOIsResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::poi_state_server::ListPOIsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::poi_state_server::ListPOIsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::poi_state_server::ListPOIsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5729bcda884e859dbb5f9dba61bed21b";
  }

  static const char* value(const ::poi_state_server::ListPOIsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5729bcda884e859dULL;
  static const uint64_t static_value2 = 0xbb5f9dba61bed21bULL;
};

template<class ContainerAllocator>
struct DataType< ::poi_state_server::ListPOIsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "poi_state_server/ListPOIsResponse";
  }

  static const char* value(const ::poi_state_server::ListPOIsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::poi_state_server::ListPOIsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"string message\n"
"poi_state_server/POIInfo[] pois\n"
"\n"
"\n"
"\n"
"================================================================================\n"
"MSG: poi_state_server/POIInfo\n"
"# POIInfo.msg\n"
"string name\n"
"string type\n"
"string description\n"
"geometry_msgs/Point position\n"
"poi_state_server/NamedPoint[] candidate_points\n"
"geometry_msgs/Point boundary_min\n"
"geometry_msgs/Point boundary_max\n"
"bool has_boundary\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: poi_state_server/NamedPoint\n"
"string name\n"
"geometry_msgs/Point point\n"
"\n"
;
  }

  static const char* value(const ::poi_state_server::ListPOIsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::poi_state_server::ListPOIsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.message);
      stream.next(m.pois);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ListPOIsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::poi_state_server::ListPOIsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::poi_state_server::ListPOIsResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.message);
    s << indent << "pois[]" << std::endl;
    for (size_t i = 0; i < v.pois.size(); ++i)
    {
      s << indent << "  pois[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::poi_state_server::POIInfo_<ContainerAllocator> >::stream(s, indent + "    ", v.pois[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // POI_STATE_SERVER_MESSAGE_LISTPOISRESPONSE_H
