// Generated by gencpp from file poi_state_server/ListPOIsRequest.msg
// DO NOT EDIT!


#ifndef POI_STATE_SERVER_MESSAGE_LISTPOISREQUEST_H
#define POI_STATE_SERVER_MESSAGE_LISTPOISREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace poi_state_server
{
template <class ContainerAllocator>
struct ListPOIsRequest_
{
  typedef ListPOIsRequest_<ContainerAllocator> Type;

  ListPOIsRequest_()
    {
    }
  ListPOIsRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::poi_state_server::ListPOIsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::poi_state_server::ListPOIsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ListPOIsRequest_

typedef ::poi_state_server::ListPOIsRequest_<std::allocator<void> > ListPOIsRequest;

typedef boost::shared_ptr< ::poi_state_server::ListPOIsRequest > ListPOIsRequestPtr;
typedef boost::shared_ptr< ::poi_state_server::ListPOIsRequest const> ListPOIsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::poi_state_server::ListPOIsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::poi_state_server::ListPOIsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace poi_state_server

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::poi_state_server::ListPOIsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::poi_state_server::ListPOIsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::poi_state_server::ListPOIsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::poi_state_server::ListPOIsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::poi_state_server::ListPOIsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::poi_state_server::ListPOIsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::poi_state_server::ListPOIsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::poi_state_server::ListPOIsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::poi_state_server::ListPOIsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "poi_state_server/ListPOIsRequest";
  }

  static const char* value(const ::poi_state_server::ListPOIsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::poi_state_server::ListPOIsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::poi_state_server::ListPOIsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::poi_state_server::ListPOIsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ListPOIsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::poi_state_server::ListPOIsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::poi_state_server::ListPOIsRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // POI_STATE_SERVER_MESSAGE_LISTPOISREQUEST_H
