// Generated by gencpp from file poi_state_server/ListPOIs.msg
// DO NOT EDIT!


#ifndef POI_STATE_SERVER_MESSAGE_LISTPOIS_H
#define POI_STATE_SERVER_MESSAGE_LISTPOIS_H

#include <ros/service_traits.h>


#include <poi_state_server/ListPOIsRequest.h>
#include <poi_state_server/ListPOIsResponse.h>


namespace poi_state_server
{

struct ListPOIs
{

typedef ListPOIsRequest Request;
typedef ListPOIsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ListPOIs
} // namespace poi_state_server


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::poi_state_server::ListPOIs > {
  static const char* value()
  {
    return "5729bcda884e859dbb5f9dba61bed21b";
  }

  static const char* value(const ::poi_state_server::ListPOIs&) { return value(); }
};

template<>
struct DataType< ::poi_state_server::ListPOIs > {
  static const char* value()
  {
    return "poi_state_server/ListPOIs";
  }

  static const char* value(const ::poi_state_server::ListPOIs&) { return value(); }
};


// service_traits::MD5Sum< ::poi_state_server::ListPOIsRequest> should match
// service_traits::MD5Sum< ::poi_state_server::ListPOIs >
template<>
struct MD5Sum< ::poi_state_server::ListPOIsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::poi_state_server::ListPOIs >::value();
  }
  static const char* value(const ::poi_state_server::ListPOIsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::poi_state_server::ListPOIsRequest> should match
// service_traits::DataType< ::poi_state_server::ListPOIs >
template<>
struct DataType< ::poi_state_server::ListPOIsRequest>
{
  static const char* value()
  {
    return DataType< ::poi_state_server::ListPOIs >::value();
  }
  static const char* value(const ::poi_state_server::ListPOIsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::poi_state_server::ListPOIsResponse> should match
// service_traits::MD5Sum< ::poi_state_server::ListPOIs >
template<>
struct MD5Sum< ::poi_state_server::ListPOIsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::poi_state_server::ListPOIs >::value();
  }
  static const char* value(const ::poi_state_server::ListPOIsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::poi_state_server::ListPOIsResponse> should match
// service_traits::DataType< ::poi_state_server::ListPOIs >
template<>
struct DataType< ::poi_state_server::ListPOIsResponse>
{
  static const char* value()
  {
    return DataType< ::poi_state_server::ListPOIs >::value();
  }
  static const char* value(const ::poi_state_server::ListPOIsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // POI_STATE_SERVER_MESSAGE_LISTPOIS_H
