// Generated by gencpp from file poi_state_server/NamedPoint.msg
// DO NOT EDIT!


#ifndef POI_STATE_SERVER_MESSAGE_NAMEDPOINT_H
#define POI_STATE_SERVER_MESSAGE_NAMEDPOINT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace poi_state_server
{
template <class ContainerAllocator>
struct NamedPoint_
{
  typedef NamedPoint_<ContainerAllocator> Type;

  NamedPoint_()
    : name()
    , point()  {
    }
  NamedPoint_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , point(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _point_type;
  _point_type point;





  typedef boost::shared_ptr< ::poi_state_server::NamedPoint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::poi_state_server::NamedPoint_<ContainerAllocator> const> ConstPtr;

}; // struct NamedPoint_

typedef ::poi_state_server::NamedPoint_<std::allocator<void> > NamedPoint;

typedef boost::shared_ptr< ::poi_state_server::NamedPoint > NamedPointPtr;
typedef boost::shared_ptr< ::poi_state_server::NamedPoint const> NamedPointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::poi_state_server::NamedPoint_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::poi_state_server::NamedPoint_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::poi_state_server::NamedPoint_<ContainerAllocator1> & lhs, const ::poi_state_server::NamedPoint_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.point == rhs.point;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::poi_state_server::NamedPoint_<ContainerAllocator1> & lhs, const ::poi_state_server::NamedPoint_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace poi_state_server

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::poi_state_server::NamedPoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::poi_state_server::NamedPoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::poi_state_server::NamedPoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::poi_state_server::NamedPoint_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::poi_state_server::NamedPoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::poi_state_server::NamedPoint_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::poi_state_server::NamedPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "679c7c057ebc773242bf1f625c1c9996";
  }

  static const char* value(const ::poi_state_server::NamedPoint_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x679c7c057ebc7732ULL;
  static const uint64_t static_value2 = 0x42bf1f625c1c9996ULL;
};

template<class ContainerAllocator>
struct DataType< ::poi_state_server::NamedPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "poi_state_server/NamedPoint";
  }

  static const char* value(const ::poi_state_server::NamedPoint_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::poi_state_server::NamedPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n"
"geometry_msgs/Point point\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::poi_state_server::NamedPoint_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::poi_state_server::NamedPoint_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.point);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NamedPoint_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::poi_state_server::NamedPoint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::poi_state_server::NamedPoint_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "point: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.point);
  }
};

} // namespace message_operations
} // namespace ros

#endif // POI_STATE_SERVER_MESSAGE_NAMEDPOINT_H
