// Generated by gencpp from file poi_state_server/POIInfo.msg
// DO NOT EDIT!


#ifndef POI_STATE_SERVER_MESSAGE_POIINFO_H
#define POI_STATE_SERVER_MESSAGE_POIINFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>
#include <poi_state_server/NamedPoint.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>

namespace poi_state_server
{
template <class ContainerAllocator>
struct POIInfo_
{
  typedef POIInfo_<ContainerAllocator> Type;

  POIInfo_()
    : name()
    , type()
    , description()
    , position()
    , candidate_points()
    , boundary_min()
    , boundary_max()
    , has_boundary(false)  {
    }
  POIInfo_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , type(_alloc)
    , description(_alloc)
    , position(_alloc)
    , candidate_points(_alloc)
    , boundary_min(_alloc)
    , boundary_max(_alloc)
    , has_boundary(false)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _type_type;
  _type_type type;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _description_type;
  _description_type description;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef std::vector< ::poi_state_server::NamedPoint_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::poi_state_server::NamedPoint_<ContainerAllocator> >::other >  _candidate_points_type;
  _candidate_points_type candidate_points;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _boundary_min_type;
  _boundary_min_type boundary_min;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _boundary_max_type;
  _boundary_max_type boundary_max;

   typedef uint8_t _has_boundary_type;
  _has_boundary_type has_boundary;





  typedef boost::shared_ptr< ::poi_state_server::POIInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::poi_state_server::POIInfo_<ContainerAllocator> const> ConstPtr;

}; // struct POIInfo_

typedef ::poi_state_server::POIInfo_<std::allocator<void> > POIInfo;

typedef boost::shared_ptr< ::poi_state_server::POIInfo > POIInfoPtr;
typedef boost::shared_ptr< ::poi_state_server::POIInfo const> POIInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::poi_state_server::POIInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::poi_state_server::POIInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::poi_state_server::POIInfo_<ContainerAllocator1> & lhs, const ::poi_state_server::POIInfo_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.type == rhs.type &&
    lhs.description == rhs.description &&
    lhs.position == rhs.position &&
    lhs.candidate_points == rhs.candidate_points &&
    lhs.boundary_min == rhs.boundary_min &&
    lhs.boundary_max == rhs.boundary_max &&
    lhs.has_boundary == rhs.has_boundary;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::poi_state_server::POIInfo_<ContainerAllocator1> & lhs, const ::poi_state_server::POIInfo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace poi_state_server

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::poi_state_server::POIInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::poi_state_server::POIInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::poi_state_server::POIInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::poi_state_server::POIInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::poi_state_server::POIInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::poi_state_server::POIInfo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::poi_state_server::POIInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4b1a999c05b4e892b655e03546fef00e";
  }

  static const char* value(const ::poi_state_server::POIInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4b1a999c05b4e892ULL;
  static const uint64_t static_value2 = 0xb655e03546fef00eULL;
};

template<class ContainerAllocator>
struct DataType< ::poi_state_server::POIInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "poi_state_server/POIInfo";
  }

  static const char* value(const ::poi_state_server::POIInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::poi_state_server::POIInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# POIInfo.msg\n"
"string name\n"
"string type\n"
"string description\n"
"geometry_msgs/Point position\n"
"poi_state_server/NamedPoint[] candidate_points\n"
"geometry_msgs/Point boundary_min\n"
"geometry_msgs/Point boundary_max\n"
"bool has_boundary\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: poi_state_server/NamedPoint\n"
"string name\n"
"geometry_msgs/Point point\n"
"\n"
;
  }

  static const char* value(const ::poi_state_server::POIInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::poi_state_server::POIInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.type);
      stream.next(m.description);
      stream.next(m.position);
      stream.next(m.candidate_points);
      stream.next(m.boundary_min);
      stream.next(m.boundary_max);
      stream.next(m.has_boundary);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct POIInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::poi_state_server::POIInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::poi_state_server::POIInfo_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.type);
    s << indent << "description: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.description);
    s << indent << "position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    s << indent << "candidate_points[]" << std::endl;
    for (size_t i = 0; i < v.candidate_points.size(); ++i)
    {
      s << indent << "  candidate_points[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::poi_state_server::NamedPoint_<ContainerAllocator> >::stream(s, indent + "    ", v.candidate_points[i]);
    }
    s << indent << "boundary_min: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.boundary_min);
    s << indent << "boundary_max: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.boundary_max);
    s << indent << "has_boundary: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.has_boundary);
  }
};

} // namespace message_operations
} // namespace ros

#endif // POI_STATE_SERVER_MESSAGE_POIINFO_H
