// Generated by gencpp from file vlm_service/CaptureImageRequest.msg
// DO NOT EDIT!


#ifndef VLM_SERVICE_MESSAGE_CAPTUREIMAGEREQUEST_H
#define VLM_SERVICE_MESSAGE_CAPTUREIMAGEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vlm_service
{
template <class ContainerAllocator>
struct CaptureImageRequest_
{
  typedef CaptureImageRequest_<ContainerAllocator> Type;

  CaptureImageRequest_()
    : directory_path()
    , file_name()
    , image_topic()  {
    }
  CaptureImageRequest_(const ContainerAllocator& _alloc)
    : directory_path(_alloc)
    , file_name(_alloc)
    , image_topic(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _directory_path_type;
  _directory_path_type directory_path;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _file_name_type;
  _file_name_type file_name;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _image_topic_type;
  _image_topic_type image_topic;





  typedef boost::shared_ptr< ::vlm_service::CaptureImageRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vlm_service::CaptureImageRequest_<ContainerAllocator> const> ConstPtr;

}; // struct CaptureImageRequest_

typedef ::vlm_service::CaptureImageRequest_<std::allocator<void> > CaptureImageRequest;

typedef boost::shared_ptr< ::vlm_service::CaptureImageRequest > CaptureImageRequestPtr;
typedef boost::shared_ptr< ::vlm_service::CaptureImageRequest const> CaptureImageRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vlm_service::CaptureImageRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vlm_service::CaptureImageRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vlm_service::CaptureImageRequest_<ContainerAllocator1> & lhs, const ::vlm_service::CaptureImageRequest_<ContainerAllocator2> & rhs)
{
  return lhs.directory_path == rhs.directory_path &&
    lhs.file_name == rhs.file_name &&
    lhs.image_topic == rhs.image_topic;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vlm_service::CaptureImageRequest_<ContainerAllocator1> & lhs, const ::vlm_service::CaptureImageRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vlm_service

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::vlm_service::CaptureImageRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vlm_service::CaptureImageRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vlm_service::CaptureImageRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vlm_service::CaptureImageRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vlm_service::CaptureImageRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vlm_service::CaptureImageRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vlm_service::CaptureImageRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c143dc1f2dad90abf4369e8bd03fce8b";
  }

  static const char* value(const ::vlm_service::CaptureImageRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc143dc1f2dad90abULL;
  static const uint64_t static_value2 = 0xf4369e8bd03fce8bULL;
};

template<class ContainerAllocator>
struct DataType< ::vlm_service::CaptureImageRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vlm_service/CaptureImageRequest";
  }

  static const char* value(const ::vlm_service::CaptureImageRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vlm_service::CaptureImageRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Request: 指定保存图像的位置和文件名\n"
"string directory_path\n"
"string file_name\n"
"string image_topic  #指定要捕获的图像话题\n"
;
  }

  static const char* value(const ::vlm_service::CaptureImageRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vlm_service::CaptureImageRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.directory_path);
      stream.next(m.file_name);
      stream.next(m.image_topic);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CaptureImageRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vlm_service::CaptureImageRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vlm_service::CaptureImageRequest_<ContainerAllocator>& v)
  {
    s << indent << "directory_path: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.directory_path);
    s << indent << "file_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.file_name);
    s << indent << "image_topic: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.image_topic);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VLM_SERVICE_MESSAGE_CAPTUREIMAGEREQUEST_H
