// Generated by gencpp from file vlm_service/DescribeSceneResponse.msg
// DO NOT EDIT!


#ifndef VLM_SERVICE_MESSAGE_DESCRIBESCENERESPONSE_H
#define VLM_SERVICE_MESSAGE_DESCRIBESCENERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vlm_service
{
template <class ContainerAllocator>
struct DescribeSceneResponse_
{
  typedef DescribeSceneResponse_<ContainerAllocator> Type;

  DescribeSceneResponse_()
    : success(false)
    , description()  {
    }
  DescribeSceneResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , description(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _description_type;
  _description_type description;





  typedef boost::shared_ptr< ::vlm_service::DescribeSceneResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vlm_service::DescribeSceneResponse_<ContainerAllocator> const> ConstPtr;

}; // struct DescribeSceneResponse_

typedef ::vlm_service::DescribeSceneResponse_<std::allocator<void> > DescribeSceneResponse;

typedef boost::shared_ptr< ::vlm_service::DescribeSceneResponse > DescribeSceneResponsePtr;
typedef boost::shared_ptr< ::vlm_service::DescribeSceneResponse const> DescribeSceneResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vlm_service::DescribeSceneResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vlm_service::DescribeSceneResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vlm_service::DescribeSceneResponse_<ContainerAllocator1> & lhs, const ::vlm_service::DescribeSceneResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.description == rhs.description;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vlm_service::DescribeSceneResponse_<ContainerAllocator1> & lhs, const ::vlm_service::DescribeSceneResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vlm_service

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::vlm_service::DescribeSceneResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vlm_service::DescribeSceneResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vlm_service::DescribeSceneResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vlm_service::DescribeSceneResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vlm_service::DescribeSceneResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vlm_service::DescribeSceneResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vlm_service::DescribeSceneResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6bccbb1e6ccd1459ac90cc79251ac541";
  }

  static const char* value(const ::vlm_service::DescribeSceneResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6bccbb1e6ccd1459ULL;
  static const uint64_t static_value2 = 0xac90cc79251ac541ULL;
};

template<class ContainerAllocator>
struct DataType< ::vlm_service::DescribeSceneResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vlm_service/DescribeSceneResponse";
  }

  static const char* value(const ::vlm_service::DescribeSceneResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vlm_service::DescribeSceneResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Response part\n"
"bool success   # 指示VLM调用是否成功\n"
"string description # VLM返回的文本描述\n"
"\n"
;
  }

  static const char* value(const ::vlm_service::DescribeSceneResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vlm_service::DescribeSceneResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.description);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DescribeSceneResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vlm_service::DescribeSceneResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vlm_service::DescribeSceneResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "description: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.description);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VLM_SERVICE_MESSAGE_DESCRIBESCENERESPONSE_H
