(cl:defpackage custom_msgs-srv
  (:use )
  (:export
   "RESETEPISODE"
   "<RESETEPISODE-REQUEST>"
   "RESETEPISODE-REQUEST"
   "<RESETEPISODE-RESPONSE>"
   "RESETEPISODE-RESPONSE"
   "UPDATECURRICULUM"
   "<UPDATECURRICULUM-REQUEST>"
   "UPDATECURRICULUM-REQUEST"
   "<UPDATECURRICULUM-RESPONSE>"
   "UPDATECURRICULUM-RESPONSE"
  ))

