// Generated by gencpp from file custom_msgs/ResetEpisodeRequest.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_RESETEPISODEREQUEST_H
#define CUSTOM_MSGS_MESSAGE_RESETEPISODEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace custom_msgs
{
template <class ContainerAllocator>
struct ResetEpisodeRequest_
{
  typedef ResetEpisodeRequest_<ContainerAllocator> Type;

  ResetEpisodeRequest_()
    {
    }
  ResetEpisodeRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::custom_msgs::ResetEpisodeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msgs::ResetEpisodeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ResetEpisodeRequest_

typedef ::custom_msgs::ResetEpisodeRequest_<std::allocator<void> > ResetEpisodeRequest;

typedef boost::shared_ptr< ::custom_msgs::ResetEpisodeRequest > ResetEpisodeRequestPtr;
typedef boost::shared_ptr< ::custom_msgs::ResetEpisodeRequest const> ResetEpisodeRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msgs::ResetEpisodeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msgs::ResetEpisodeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace custom_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::ResetEpisodeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::ResetEpisodeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::ResetEpisodeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::ResetEpisodeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::ResetEpisodeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::ResetEpisodeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msgs::ResetEpisodeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::custom_msgs::ResetEpisodeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msgs::ResetEpisodeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msgs/ResetEpisodeRequest";
  }

  static const char* value(const ::custom_msgs::ResetEpisodeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msgs::ResetEpisodeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# custom_msgs/srv/ResetEpisode.srv\n"
"\n"
"# --- Request ---\n"
"# 请求可以是空的，因为我们只是想触发一个重置\n"
"# 可以加一个bool来支持课程学习，但现在先保持简单\n"
"# bool use_curriculum\n"
"\n"
;
  }

  static const char* value(const ::custom_msgs::ResetEpisodeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msgs::ResetEpisodeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ResetEpisodeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msgs::ResetEpisodeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::custom_msgs::ResetEpisodeRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_RESETEPISODEREQUEST_H
