// Generated by gencpp from file custom_msgs/ResetEpisode.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_RESETEPISODE_H
#define CUSTOM_MSGS_MESSAGE_RESETEPISODE_H

#include <ros/service_traits.h>


#include <custom_msgs/ResetEpisodeRequest.h>
#include <custom_msgs/ResetEpisodeResponse.h>


namespace custom_msgs
{

struct ResetEpisode
{

typedef ResetEpisodeRequest Request;
typedef ResetEpisodeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ResetEpisode
} // namespace custom_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::custom_msgs::ResetEpisode > {
  static const char* value()
  {
    return "e566690f9c9e0029132e05fa58e0f836";
  }

  static const char* value(const ::custom_msgs::ResetEpisode&) { return value(); }
};

template<>
struct DataType< ::custom_msgs::ResetEpisode > {
  static const char* value()
  {
    return "custom_msgs/ResetEpisode";
  }

  static const char* value(const ::custom_msgs::ResetEpisode&) { return value(); }
};


// service_traits::MD5Sum< ::custom_msgs::ResetEpisodeRequest> should match
// service_traits::MD5Sum< ::custom_msgs::ResetEpisode >
template<>
struct MD5Sum< ::custom_msgs::ResetEpisodeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::custom_msgs::ResetEpisode >::value();
  }
  static const char* value(const ::custom_msgs::ResetEpisodeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::custom_msgs::ResetEpisodeRequest> should match
// service_traits::DataType< ::custom_msgs::ResetEpisode >
template<>
struct DataType< ::custom_msgs::ResetEpisodeRequest>
{
  static const char* value()
  {
    return DataType< ::custom_msgs::ResetEpisode >::value();
  }
  static const char* value(const ::custom_msgs::ResetEpisodeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::custom_msgs::ResetEpisodeResponse> should match
// service_traits::MD5Sum< ::custom_msgs::ResetEpisode >
template<>
struct MD5Sum< ::custom_msgs::ResetEpisodeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::custom_msgs::ResetEpisode >::value();
  }
  static const char* value(const ::custom_msgs::ResetEpisodeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::custom_msgs::ResetEpisodeResponse> should match
// service_traits::DataType< ::custom_msgs::ResetEpisode >
template<>
struct DataType< ::custom_msgs::ResetEpisodeResponse>
{
  static const char* value()
  {
    return DataType< ::custom_msgs::ResetEpisode >::value();
  }
  static const char* value(const ::custom_msgs::ResetEpisodeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_RESETEPISODE_H
