// Generated by gencpp from file custom_msgs/UpdateCurriculumRequest.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_UPDATECURRICULUMREQUEST_H
#define CUSTOM_MSGS_MESSAGE_UPDATECURRICULUMREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace custom_msgs
{
template <class ContainerAllocator>
struct UpdateCurriculumRequest_
{
  typedef UpdateCurriculumRequest_<ContainerAllocator> Type;

  UpdateCurriculumRequest_()
    : spawn_range_x(0.0)
    , spawn_range_z(0.0)
    , local_target_range(0.0)  {
    }
  UpdateCurriculumRequest_(const ContainerAllocator& _alloc)
    : spawn_range_x(0.0)
    , spawn_range_z(0.0)
    , local_target_range(0.0)  {
  (void)_alloc;
    }



   typedef float _spawn_range_x_type;
  _spawn_range_x_type spawn_range_x;

   typedef float _spawn_range_z_type;
  _spawn_range_z_type spawn_range_z;

   typedef float _local_target_range_type;
  _local_target_range_type local_target_range;





  typedef boost::shared_ptr< ::custom_msgs::UpdateCurriculumRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msgs::UpdateCurriculumRequest_<ContainerAllocator> const> ConstPtr;

}; // struct UpdateCurriculumRequest_

typedef ::custom_msgs::UpdateCurriculumRequest_<std::allocator<void> > UpdateCurriculumRequest;

typedef boost::shared_ptr< ::custom_msgs::UpdateCurriculumRequest > UpdateCurriculumRequestPtr;
typedef boost::shared_ptr< ::custom_msgs::UpdateCurriculumRequest const> UpdateCurriculumRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msgs::UpdateCurriculumRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msgs::UpdateCurriculumRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::custom_msgs::UpdateCurriculumRequest_<ContainerAllocator1> & lhs, const ::custom_msgs::UpdateCurriculumRequest_<ContainerAllocator2> & rhs)
{
  return lhs.spawn_range_x == rhs.spawn_range_x &&
    lhs.spawn_range_z == rhs.spawn_range_z &&
    lhs.local_target_range == rhs.local_target_range;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::custom_msgs::UpdateCurriculumRequest_<ContainerAllocator1> & lhs, const ::custom_msgs::UpdateCurriculumRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace custom_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::UpdateCurriculumRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::UpdateCurriculumRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::UpdateCurriculumRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::UpdateCurriculumRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::UpdateCurriculumRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::UpdateCurriculumRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msgs::UpdateCurriculumRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bb353952b83dc48c2837dbeebad71ee4";
  }

  static const char* value(const ::custom_msgs::UpdateCurriculumRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbb353952b83dc48cULL;
  static const uint64_t static_value2 = 0x2837dbeebad71ee4ULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msgs::UpdateCurriculumRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msgs/UpdateCurriculumRequest";
  }

  static const char* value(const ::custom_msgs::UpdateCurriculumRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msgs::UpdateCurriculumRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 spawn_range_x\n"
"float32 spawn_range_z\n"
"float32 local_target_range\n"
;
  }

  static const char* value(const ::custom_msgs::UpdateCurriculumRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msgs::UpdateCurriculumRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.spawn_range_x);
      stream.next(m.spawn_range_z);
      stream.next(m.local_target_range);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct UpdateCurriculumRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msgs::UpdateCurriculumRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msgs::UpdateCurriculumRequest_<ContainerAllocator>& v)
  {
    s << indent << "spawn_range_x: ";
    Printer<float>::stream(s, indent + "  ", v.spawn_range_x);
    s << indent << "spawn_range_z: ";
    Printer<float>::stream(s, indent + "  ", v.spawn_range_z);
    s << indent << "local_target_range: ";
    Printer<float>::stream(s, indent + "  ", v.local_target_range);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_UPDATECURRICULUMREQUEST_H
