// Generated by gencpp from file custom_msgs/UpdateCurriculum.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_UPDATECURRICULUM_H
#define CUSTOM_MSGS_MESSAGE_UPDATECURRICULUM_H

#include <ros/service_traits.h>


#include <custom_msgs/UpdateCurriculumRequest.h>
#include <custom_msgs/UpdateCurriculumResponse.h>


namespace custom_msgs
{

struct UpdateCurriculum
{

typedef UpdateCurriculumRequest Request;
typedef UpdateCurriculumResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct UpdateCurriculum
} // namespace custom_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::custom_msgs::UpdateCurriculum > {
  static const char* value()
  {
    return "3b2cd8798f0550ceaa4d103980369410";
  }

  static const char* value(const ::custom_msgs::UpdateCurriculum&) { return value(); }
};

template<>
struct DataType< ::custom_msgs::UpdateCurriculum > {
  static const char* value()
  {
    return "custom_msgs/UpdateCurriculum";
  }

  static const char* value(const ::custom_msgs::UpdateCurriculum&) { return value(); }
};


// service_traits::MD5Sum< ::custom_msgs::UpdateCurriculumRequest> should match
// service_traits::MD5Sum< ::custom_msgs::UpdateCurriculum >
template<>
struct MD5Sum< ::custom_msgs::UpdateCurriculumRequest>
{
  static const char* value()
  {
    return MD5Sum< ::custom_msgs::UpdateCurriculum >::value();
  }
  static const char* value(const ::custom_msgs::UpdateCurriculumRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::custom_msgs::UpdateCurriculumRequest> should match
// service_traits::DataType< ::custom_msgs::UpdateCurriculum >
template<>
struct DataType< ::custom_msgs::UpdateCurriculumRequest>
{
  static const char* value()
  {
    return DataType< ::custom_msgs::UpdateCurriculum >::value();
  }
  static const char* value(const ::custom_msgs::UpdateCurriculumRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::custom_msgs::UpdateCurriculumResponse> should match
// service_traits::MD5Sum< ::custom_msgs::UpdateCurriculum >
template<>
struct MD5Sum< ::custom_msgs::UpdateCurriculumResponse>
{
  static const char* value()
  {
    return MD5Sum< ::custom_msgs::UpdateCurriculum >::value();
  }
  static const char* value(const ::custom_msgs::UpdateCurriculumResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::custom_msgs::UpdateCurriculumResponse> should match
// service_traits::DataType< ::custom_msgs::UpdateCurriculum >
template<>
struct DataType< ::custom_msgs::UpdateCurriculumResponse>
{
  static const char* value()
  {
    return DataType< ::custom_msgs::UpdateCurriculum >::value();
  }
  static const char* value(const ::custom_msgs::UpdateCurriculumResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_UPDATECURRICULUM_H
