// Generated by gencpp from file nlp_drone_control/Action.msg
// DO NOT EDIT!


#ifndef NLP_DRONE_CONTROL_MESSAGE_ACTION_H
#define NLP_DRONE_CONTROL_MESSAGE_ACTION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace nlp_drone_control
{
template <class ContainerAllocator>
struct Action_
{
  typedef Action_<ContainerAllocator> Type;

  Action_()
    : function_name()
    , arguments_json()  {
    }
  Action_(const ContainerAllocator& _alloc)
    : function_name(_alloc)
    , arguments_json(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _function_name_type;
  _function_name_type function_name;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _arguments_json_type;
  _arguments_json_type arguments_json;





  typedef boost::shared_ptr< ::nlp_drone_control::Action_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nlp_drone_control::Action_<ContainerAllocator> const> ConstPtr;

}; // struct Action_

typedef ::nlp_drone_control::Action_<std::allocator<void> > Action;

typedef boost::shared_ptr< ::nlp_drone_control::Action > ActionPtr;
typedef boost::shared_ptr< ::nlp_drone_control::Action const> ActionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nlp_drone_control::Action_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nlp_drone_control::Action_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::nlp_drone_control::Action_<ContainerAllocator1> & lhs, const ::nlp_drone_control::Action_<ContainerAllocator2> & rhs)
{
  return lhs.function_name == rhs.function_name &&
    lhs.arguments_json == rhs.arguments_json;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::nlp_drone_control::Action_<ContainerAllocator1> & lhs, const ::nlp_drone_control::Action_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace nlp_drone_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::nlp_drone_control::Action_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nlp_drone_control::Action_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nlp_drone_control::Action_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nlp_drone_control::Action_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nlp_drone_control::Action_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nlp_drone_control::Action_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nlp_drone_control::Action_<ContainerAllocator> >
{
  static const char* value()
  {
    return "45955b02be53f69e3133212fb3d15576";
  }

  static const char* value(const ::nlp_drone_control::Action_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x45955b02be53f69eULL;
  static const uint64_t static_value2 = 0x3133212fb3d15576ULL;
};

template<class ContainerAllocator>
struct DataType< ::nlp_drone_control::Action_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nlp_drone_control/Action";
  }

  static const char* value(const ::nlp_drone_control::Action_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nlp_drone_control::Action_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Represents a single tool call produced by the LLM\n"
"string function_name       # e.g. \"takeoff\"\n"
"string arguments_json      # raw JSON string of arguments\n"
"\n"
;
  }

  static const char* value(const ::nlp_drone_control::Action_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nlp_drone_control::Action_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.function_name);
      stream.next(m.arguments_json);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Action_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nlp_drone_control::Action_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nlp_drone_control::Action_<ContainerAllocator>& v)
  {
    s << indent << "function_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.function_name);
    s << indent << "arguments_json: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.arguments_json);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NLP_DRONE_CONTROL_MESSAGE_ACTION_H
