// Generated by gencpp from file nlp_drone_control/ExecuteDroneAction.msg
// DO NOT EDIT!


#ifndef NLP_DRONE_CONTROL_MESSAGE_EXECUTEDRONEACTION_H
#define NLP_DRONE_CONTROL_MESSAGE_EXECUTEDRONEACTION_H

#include <ros/service_traits.h>


#include <nlp_drone_control/ExecuteDroneActionRequest.h>
#include <nlp_drone_control/ExecuteDroneActionResponse.h>


namespace nlp_drone_control
{

struct ExecuteDroneAction
{

typedef ExecuteDroneActionRequest Request;
typedef ExecuteDroneActionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ExecuteDroneAction
} // namespace nlp_drone_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::nlp_drone_control::ExecuteDroneAction > {
  static const char* value()
  {
    return "77584cf99b7cb35fa13143d3f49ac104";
  }

  static const char* value(const ::nlp_drone_control::ExecuteDroneAction&) { return value(); }
};

template<>
struct DataType< ::nlp_drone_control::ExecuteDroneAction > {
  static const char* value()
  {
    return "nlp_drone_control/ExecuteDroneAction";
  }

  static const char* value(const ::nlp_drone_control::ExecuteDroneAction&) { return value(); }
};


// service_traits::MD5Sum< ::nlp_drone_control::ExecuteDroneActionRequest> should match
// service_traits::MD5Sum< ::nlp_drone_control::ExecuteDroneAction >
template<>
struct MD5Sum< ::nlp_drone_control::ExecuteDroneActionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::nlp_drone_control::ExecuteDroneAction >::value();
  }
  static const char* value(const ::nlp_drone_control::ExecuteDroneActionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::nlp_drone_control::ExecuteDroneActionRequest> should match
// service_traits::DataType< ::nlp_drone_control::ExecuteDroneAction >
template<>
struct DataType< ::nlp_drone_control::ExecuteDroneActionRequest>
{
  static const char* value()
  {
    return DataType< ::nlp_drone_control::ExecuteDroneAction >::value();
  }
  static const char* value(const ::nlp_drone_control::ExecuteDroneActionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::nlp_drone_control::ExecuteDroneActionResponse> should match
// service_traits::MD5Sum< ::nlp_drone_control::ExecuteDroneAction >
template<>
struct MD5Sum< ::nlp_drone_control::ExecuteDroneActionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::nlp_drone_control::ExecuteDroneAction >::value();
  }
  static const char* value(const ::nlp_drone_control::ExecuteDroneActionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::nlp_drone_control::ExecuteDroneActionResponse> should match
// service_traits::DataType< ::nlp_drone_control::ExecuteDroneAction >
template<>
struct DataType< ::nlp_drone_control::ExecuteDroneActionResponse>
{
  static const char* value()
  {
    return DataType< ::nlp_drone_control::ExecuteDroneAction >::value();
  }
  static const char* value(const ::nlp_drone_control::ExecuteDroneActionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NLP_DRONE_CONTROL_MESSAGE_EXECUTEDRONEACTION_H
