// Generated by gencpp from file nlp_drone_control/ExecuteDroneActionResponse.msg
// DO NOT EDIT!


#ifndef NLP_DRONE_CONTROL_MESSAGE_EXECUTEDRONEACTIONRESPONSE_H
#define NLP_DRONE_CONTROL_MESSAGE_EXECUTEDRONEACTIONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace nlp_drone_control
{
template <class ContainerAllocator>
struct ExecuteDroneActionResponse_
{
  typedef ExecuteDroneActionResponse_<ContainerAllocator> Type;

  ExecuteDroneActionResponse_()
    : success(false)
    , message()  {
    }
  ExecuteDroneActionResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::nlp_drone_control::ExecuteDroneActionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nlp_drone_control::ExecuteDroneActionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ExecuteDroneActionResponse_

typedef ::nlp_drone_control::ExecuteDroneActionResponse_<std::allocator<void> > ExecuteDroneActionResponse;

typedef boost::shared_ptr< ::nlp_drone_control::ExecuteDroneActionResponse > ExecuteDroneActionResponsePtr;
typedef boost::shared_ptr< ::nlp_drone_control::ExecuteDroneActionResponse const> ExecuteDroneActionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nlp_drone_control::ExecuteDroneActionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nlp_drone_control::ExecuteDroneActionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::nlp_drone_control::ExecuteDroneActionResponse_<ContainerAllocator1> & lhs, const ::nlp_drone_control::ExecuteDroneActionResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::nlp_drone_control::ExecuteDroneActionResponse_<ContainerAllocator1> & lhs, const ::nlp_drone_control::ExecuteDroneActionResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace nlp_drone_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::nlp_drone_control::ExecuteDroneActionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nlp_drone_control::ExecuteDroneActionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nlp_drone_control::ExecuteDroneActionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nlp_drone_control::ExecuteDroneActionResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nlp_drone_control::ExecuteDroneActionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nlp_drone_control::ExecuteDroneActionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nlp_drone_control::ExecuteDroneActionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "937c9679a518e3a18d831e57125ea522";
  }

  static const char* value(const ::nlp_drone_control::ExecuteDroneActionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x937c9679a518e3a1ULL;
  static const uint64_t static_value2 = 0x8d831e57125ea522ULL;
};

template<class ContainerAllocator>
struct DataType< ::nlp_drone_control::ExecuteDroneActionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nlp_drone_control/ExecuteDroneActionResponse";
  }

  static const char* value(const ::nlp_drone_control::ExecuteDroneActionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nlp_drone_control::ExecuteDroneActionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# --- Response ---\n"
"bool success          # 动作是否成功执行\n"
"string message        # 返回给LLM的信息，例如 \"Camera adjusted.\" 或 \"Rotation failed.\"\n"
"\n"
;
  }

  static const char* value(const ::nlp_drone_control::ExecuteDroneActionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nlp_drone_control::ExecuteDroneActionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ExecuteDroneActionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nlp_drone_control::ExecuteDroneActionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nlp_drone_control::ExecuteDroneActionResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NLP_DRONE_CONTROL_MESSAGE_EXECUTEDRONEACTIONRESPONSE_H
