// Generated by gencpp from file nlp_drone_control/Plan.msg
// DO NOT EDIT!


#ifndef NLP_DRONE_CONTROL_MESSAGE_PLAN_H
#define NLP_DRONE_CONTROL_MESSAGE_PLAN_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <nlp_drone_control/Action.h>

namespace nlp_drone_control
{
template <class ContainerAllocator>
struct Plan_
{
  typedef Plan_<ContainerAllocator> Type;

  Plan_()
    : actions()
    , replan_mode(0)  {
    }
  Plan_(const ContainerAllocator& _alloc)
    : actions(_alloc)
    , replan_mode(0)  {
  (void)_alloc;
    }



   typedef std::vector< ::nlp_drone_control::Action_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::nlp_drone_control::Action_<ContainerAllocator> >::other >  _actions_type;
  _actions_type actions;

   typedef uint8_t _replan_mode_type;
  _replan_mode_type replan_mode;





  typedef boost::shared_ptr< ::nlp_drone_control::Plan_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nlp_drone_control::Plan_<ContainerAllocator> const> ConstPtr;

}; // struct Plan_

typedef ::nlp_drone_control::Plan_<std::allocator<void> > Plan;

typedef boost::shared_ptr< ::nlp_drone_control::Plan > PlanPtr;
typedef boost::shared_ptr< ::nlp_drone_control::Plan const> PlanConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nlp_drone_control::Plan_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nlp_drone_control::Plan_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::nlp_drone_control::Plan_<ContainerAllocator1> & lhs, const ::nlp_drone_control::Plan_<ContainerAllocator2> & rhs)
{
  return lhs.actions == rhs.actions &&
    lhs.replan_mode == rhs.replan_mode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::nlp_drone_control::Plan_<ContainerAllocator1> & lhs, const ::nlp_drone_control::Plan_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace nlp_drone_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::nlp_drone_control::Plan_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nlp_drone_control::Plan_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nlp_drone_control::Plan_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nlp_drone_control::Plan_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nlp_drone_control::Plan_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nlp_drone_control::Plan_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nlp_drone_control::Plan_<ContainerAllocator> >
{
  static const char* value()
  {
    return "13f0666e18573937822408eb65c6a4cd";
  }

  static const char* value(const ::nlp_drone_control::Plan_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x13f0666e18573937ULL;
  static const uint64_t static_value2 = 0x822408eb65c6a4cdULL;
};

template<class ContainerAllocator>
struct DataType< ::nlp_drone_control::Plan_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nlp_drone_control/Plan";
  }

  static const char* value(const ::nlp_drone_control::Plan_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nlp_drone_control::Plan_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Represents a list of tool calls (a full execution plan)\n"
"nlp_drone_control/Action[] actions\n"
"uint8 replan_mode          # 0 = APPEND, 1 = REPLACE\n"
"\n"
"\n"
"================================================================================\n"
"MSG: nlp_drone_control/Action\n"
"# Represents a single tool call produced by the LLM\n"
"string function_name       # e.g. \"takeoff\"\n"
"string arguments_json      # raw JSON string of arguments\n"
"\n"
;
  }

  static const char* value(const ::nlp_drone_control::Plan_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nlp_drone_control::Plan_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.actions);
      stream.next(m.replan_mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Plan_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nlp_drone_control::Plan_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nlp_drone_control::Plan_<ContainerAllocator>& v)
  {
    s << indent << "actions[]" << std::endl;
    for (size_t i = 0; i < v.actions.size(); ++i)
    {
      s << indent << "  actions[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::nlp_drone_control::Action_<ContainerAllocator> >::stream(s, indent + "    ", v.actions[i]);
    }
    s << indent << "replan_mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.replan_mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NLP_DRONE_CONTROL_MESSAGE_PLAN_H
