// Generated by gencpp from file rl_bridge/CurriculumStatus.msg
// DO NOT EDIT!


#ifndef RL_BRIDGE_MESSAGE_CURRICULUMSTATUS_H
#define RL_BRIDGE_MESSAGE_CURRICULUMSTATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rl_bridge
{
template <class ContainerAllocator>
struct CurriculumStatus_
{
  typedef CurriculumStatus_<ContainerAllocator> Type;

  CurriculumStatus_()
    : lesson_id(0)
    , lesson_name()
    , changed(false)  {
    }
  CurriculumStatus_(const ContainerAllocator& _alloc)
    : lesson_id(0)
    , lesson_name(_alloc)
    , changed(false)  {
  (void)_alloc;
    }



   typedef int32_t _lesson_id_type;
  _lesson_id_type lesson_id;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _lesson_name_type;
  _lesson_name_type lesson_name;

   typedef uint8_t _changed_type;
  _changed_type changed;





  typedef boost::shared_ptr< ::rl_bridge::CurriculumStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rl_bridge::CurriculumStatus_<ContainerAllocator> const> ConstPtr;

}; // struct CurriculumStatus_

typedef ::rl_bridge::CurriculumStatus_<std::allocator<void> > CurriculumStatus;

typedef boost::shared_ptr< ::rl_bridge::CurriculumStatus > CurriculumStatusPtr;
typedef boost::shared_ptr< ::rl_bridge::CurriculumStatus const> CurriculumStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rl_bridge::CurriculumStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rl_bridge::CurriculumStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rl_bridge::CurriculumStatus_<ContainerAllocator1> & lhs, const ::rl_bridge::CurriculumStatus_<ContainerAllocator2> & rhs)
{
  return lhs.lesson_id == rhs.lesson_id &&
    lhs.lesson_name == rhs.lesson_name &&
    lhs.changed == rhs.changed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rl_bridge::CurriculumStatus_<ContainerAllocator1> & lhs, const ::rl_bridge::CurriculumStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rl_bridge

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rl_bridge::CurriculumStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rl_bridge::CurriculumStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rl_bridge::CurriculumStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rl_bridge::CurriculumStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rl_bridge::CurriculumStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rl_bridge::CurriculumStatus_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rl_bridge::CurriculumStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eed77d69c41fbfca0645d6c4f9105016";
  }

  static const char* value(const ::rl_bridge::CurriculumStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeed77d69c41fbfcaULL;
  static const uint64_t static_value2 = 0x0645d6c4f9105016ULL;
};

template<class ContainerAllocator>
struct DataType< ::rl_bridge::CurriculumStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rl_bridge/CurriculumStatus";
  }

  static const char* value(const ::rl_bridge::CurriculumStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rl_bridge::CurriculumStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"int32 lesson_id\n"
"string lesson_name\n"
"bool changed\n"
"\n"
"\n"
;
  }

  static const char* value(const ::rl_bridge::CurriculumStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rl_bridge::CurriculumStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.lesson_id);
      stream.next(m.lesson_name);
      stream.next(m.changed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CurriculumStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rl_bridge::CurriculumStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rl_bridge::CurriculumStatus_<ContainerAllocator>& v)
  {
    s << indent << "lesson_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.lesson_id);
    s << indent << "lesson_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.lesson_name);
    s << indent << "changed: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.changed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RL_BRIDGE_MESSAGE_CURRICULUMSTATUS_H
