// Generated by gencpp from file rl_bridge/RLAction.msg
// DO NOT EDIT!


#ifndef RL_BRIDGE_MESSAGE_RLACTION_H
#define RL_BRIDGE_MESSAGE_RLACTION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rl_bridge
{
template <class ContainerAllocator>
struct RLAction_
{
  typedef RLAction_<ContainerAllocator> Type;

  RLAction_()
    : ax(0.0)
    , ay(0.0)  {
    }
  RLAction_(const ContainerAllocator& _alloc)
    : ax(0.0)
    , ay(0.0)  {
  (void)_alloc;
    }



   typedef float _ax_type;
  _ax_type ax;

   typedef float _ay_type;
  _ay_type ay;





  typedef boost::shared_ptr< ::rl_bridge::RLAction_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rl_bridge::RLAction_<ContainerAllocator> const> ConstPtr;

}; // struct RLAction_

typedef ::rl_bridge::RLAction_<std::allocator<void> > RLAction;

typedef boost::shared_ptr< ::rl_bridge::RLAction > RLActionPtr;
typedef boost::shared_ptr< ::rl_bridge::RLAction const> RLActionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rl_bridge::RLAction_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rl_bridge::RLAction_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rl_bridge::RLAction_<ContainerAllocator1> & lhs, const ::rl_bridge::RLAction_<ContainerAllocator2> & rhs)
{
  return lhs.ax == rhs.ax &&
    lhs.ay == rhs.ay;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rl_bridge::RLAction_<ContainerAllocator1> & lhs, const ::rl_bridge::RLAction_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rl_bridge

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rl_bridge::RLAction_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rl_bridge::RLAction_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rl_bridge::RLAction_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rl_bridge::RLAction_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rl_bridge::RLAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rl_bridge::RLAction_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rl_bridge::RLAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4eb4e8d132b979f0df69e04e0a241d57";
  }

  static const char* value(const ::rl_bridge::RLAction_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4eb4e8d132b979f0ULL;
  static const uint64_t static_value2 = 0xdf69e04e0a241d57ULL;
};

template<class ContainerAllocator>
struct DataType< ::rl_bridge::RLAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rl_bridge/RLAction";
  }

  static const char* value(const ::rl_bridge::RLAction_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rl_bridge::RLAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 ax\n"
"float32 ay\n"
"\n"
;
  }

  static const char* value(const ::rl_bridge::RLAction_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rl_bridge::RLAction_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ax);
      stream.next(m.ay);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RLAction_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rl_bridge::RLAction_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rl_bridge::RLAction_<ContainerAllocator>& v)
  {
    s << indent << "ax: ";
    Printer<float>::stream(s, indent + "  ", v.ax);
    s << indent << "ay: ";
    Printer<float>::stream(s, indent + "  ", v.ay);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RL_BRIDGE_MESSAGE_RLACTION_H
