// Generated by gencpp from file rl_bridge/RLDone.msg
// DO NOT EDIT!


#ifndef RL_BRIDGE_MESSAGE_RLDONE_H
#define RL_BRIDGE_MESSAGE_RLDONE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rl_bridge
{
template <class ContainerAllocator>
struct RLDone_
{
  typedef RLDone_<ContainerAllocator> Type;

  RLDone_()
    : done(false)  {
    }
  RLDone_(const ContainerAllocator& _alloc)
    : done(false)  {
  (void)_alloc;
    }



   typedef uint8_t _done_type;
  _done_type done;





  typedef boost::shared_ptr< ::rl_bridge::RLDone_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rl_bridge::RLDone_<ContainerAllocator> const> ConstPtr;

}; // struct RLDone_

typedef ::rl_bridge::RLDone_<std::allocator<void> > RLDone;

typedef boost::shared_ptr< ::rl_bridge::RLDone > RLDonePtr;
typedef boost::shared_ptr< ::rl_bridge::RLDone const> RLDoneConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rl_bridge::RLDone_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rl_bridge::RLDone_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rl_bridge::RLDone_<ContainerAllocator1> & lhs, const ::rl_bridge::RLDone_<ContainerAllocator2> & rhs)
{
  return lhs.done == rhs.done;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rl_bridge::RLDone_<ContainerAllocator1> & lhs, const ::rl_bridge::RLDone_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rl_bridge

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rl_bridge::RLDone_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rl_bridge::RLDone_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rl_bridge::RLDone_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rl_bridge::RLDone_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rl_bridge::RLDone_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rl_bridge::RLDone_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rl_bridge::RLDone_<ContainerAllocator> >
{
  static const char* value()
  {
    return "89bb254424e4cffedbf494e7b0ddbfea";
  }

  static const char* value(const ::rl_bridge::RLDone_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x89bb254424e4cffeULL;
  static const uint64_t static_value2 = 0xdbf494e7b0ddbfeaULL;
};

template<class ContainerAllocator>
struct DataType< ::rl_bridge::RLDone_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rl_bridge/RLDone";
  }

  static const char* value(const ::rl_bridge::RLDone_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rl_bridge::RLDone_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool done\n"
;
  }

  static const char* value(const ::rl_bridge::RLDone_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rl_bridge::RLDone_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.done);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RLDone_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rl_bridge::RLDone_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rl_bridge::RLDone_<ContainerAllocator>& v)
  {
    s << indent << "done: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.done);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RL_BRIDGE_MESSAGE_RLDONE_H
