// Generated by gencpp from file rl_bridge/RLEvent.msg
// DO NOT EDIT!


#ifndef RL_BRIDGE_MESSAGE_RLEVENT_H
#define RL_BRIDGE_MESSAGE_RLEVENT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rl_bridge
{
template <class ContainerAllocator>
struct RLEvent_
{
  typedef RLEvent_<ContainerAllocator> Type;

  RLEvent_()
    : event_type()
    , data()
    , done(false)  {
    }
  RLEvent_(const ContainerAllocator& _alloc)
    : event_type(_alloc)
    , data(_alloc)
    , done(false)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _event_type_type;
  _event_type_type event_type;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _data_type;
  _data_type data;

   typedef uint8_t _done_type;
  _done_type done;





  typedef boost::shared_ptr< ::rl_bridge::RLEvent_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rl_bridge::RLEvent_<ContainerAllocator> const> ConstPtr;

}; // struct RLEvent_

typedef ::rl_bridge::RLEvent_<std::allocator<void> > RLEvent;

typedef boost::shared_ptr< ::rl_bridge::RLEvent > RLEventPtr;
typedef boost::shared_ptr< ::rl_bridge::RLEvent const> RLEventConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rl_bridge::RLEvent_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rl_bridge::RLEvent_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rl_bridge::RLEvent_<ContainerAllocator1> & lhs, const ::rl_bridge::RLEvent_<ContainerAllocator2> & rhs)
{
  return lhs.event_type == rhs.event_type &&
    lhs.data == rhs.data &&
    lhs.done == rhs.done;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rl_bridge::RLEvent_<ContainerAllocator1> & lhs, const ::rl_bridge::RLEvent_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rl_bridge

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rl_bridge::RLEvent_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rl_bridge::RLEvent_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rl_bridge::RLEvent_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rl_bridge::RLEvent_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rl_bridge::RLEvent_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rl_bridge::RLEvent_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rl_bridge::RLEvent_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3d11c09bdebe9d87801e4c84e2840393";
  }

  static const char* value(const ::rl_bridge::RLEvent_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3d11c09bdebe9d87ULL;
  static const uint64_t static_value2 = 0x801e4c84e2840393ULL;
};

template<class ContainerAllocator>
struct DataType< ::rl_bridge::RLEvent_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rl_bridge/RLEvent";
  }

  static const char* value(const ::rl_bridge::RLEvent_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rl_bridge::RLEvent_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# RLEvent.msg\n"
"\n"
"string event_type         # 事件类型，例如 \"move\", \"reached_target\", \"collision\", \"out_of_bounds\"\n"
"float32[] data            # 附带数据，例如 [distance, velocity, angle]\n"
"bool done                 # 是否终止当前 episode\n"
"\n"
;
  }

  static const char* value(const ::rl_bridge::RLEvent_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rl_bridge::RLEvent_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.event_type);
      stream.next(m.data);
      stream.next(m.done);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RLEvent_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rl_bridge::RLEvent_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rl_bridge::RLEvent_<ContainerAllocator>& v)
  {
    s << indent << "event_type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.event_type);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.data[i]);
    }
    s << indent << "done: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.done);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RL_BRIDGE_MESSAGE_RLEVENT_H
