// Generated by gencpp from file rl_bridge/RLObservation.msg
// DO NOT EDIT!


#ifndef RL_BRIDGE_MESSAGE_RLOBSERVATION_H
#define RL_BRIDGE_MESSAGE_RLOBSERVATION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rl_bridge
{
template <class ContainerAllocator>
struct RLObservation_
{
  typedef RLObservation_<ContainerAllocator> Type;

  RLObservation_()
    : x(0.0)
    , y(0.0)
    , vx(0.0)
    , vy(0.0)  {
    }
  RLObservation_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , vx(0.0)
    , vy(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _vx_type;
  _vx_type vx;

   typedef float _vy_type;
  _vy_type vy;





  typedef boost::shared_ptr< ::rl_bridge::RLObservation_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rl_bridge::RLObservation_<ContainerAllocator> const> ConstPtr;

}; // struct RLObservation_

typedef ::rl_bridge::RLObservation_<std::allocator<void> > RLObservation;

typedef boost::shared_ptr< ::rl_bridge::RLObservation > RLObservationPtr;
typedef boost::shared_ptr< ::rl_bridge::RLObservation const> RLObservationConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rl_bridge::RLObservation_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rl_bridge::RLObservation_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rl_bridge::RLObservation_<ContainerAllocator1> & lhs, const ::rl_bridge::RLObservation_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.vx == rhs.vx &&
    lhs.vy == rhs.vy;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rl_bridge::RLObservation_<ContainerAllocator1> & lhs, const ::rl_bridge::RLObservation_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rl_bridge

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rl_bridge::RLObservation_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rl_bridge::RLObservation_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rl_bridge::RLObservation_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rl_bridge::RLObservation_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rl_bridge::RLObservation_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rl_bridge::RLObservation_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rl_bridge::RLObservation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2af08925b9da4c99c24669eae33385e8";
  }

  static const char* value(const ::rl_bridge::RLObservation_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2af08925b9da4c99ULL;
  static const uint64_t static_value2 = 0xc24669eae33385e8ULL;
};

template<class ContainerAllocator>
struct DataType< ::rl_bridge::RLObservation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rl_bridge/RLObservation";
  }

  static const char* value(const ::rl_bridge::RLObservation_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rl_bridge::RLObservation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n"
"float32 y\n"
"float32 vx\n"
"float32 vy\n"
"\n"
;
  }

  static const char* value(const ::rl_bridge::RLObservation_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rl_bridge::RLObservation_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.vx);
      stream.next(m.vy);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RLObservation_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rl_bridge::RLObservation_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rl_bridge::RLObservation_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "vx: ";
    Printer<float>::stream(s, indent + "  ", v.vx);
    s << indent << "vy: ";
    Printer<float>::stream(s, indent + "  ", v.vy);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RL_BRIDGE_MESSAGE_RLOBSERVATION_H
