// Generated by gencpp from file rl_bridge/RLReset.msg
// DO NOT EDIT!


#ifndef RL_BRIDGE_MESSAGE_RLRESET_H
#define RL_BRIDGE_MESSAGE_RLRESET_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rl_bridge
{
template <class ContainerAllocator>
struct RLReset_
{
  typedef RLReset_<ContainerAllocator> Type;

  RLReset_()
    : reset(false)  {
    }
  RLReset_(const ContainerAllocator& _alloc)
    : reset(false)  {
  (void)_alloc;
    }



   typedef uint8_t _reset_type;
  _reset_type reset;





  typedef boost::shared_ptr< ::rl_bridge::RLReset_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rl_bridge::RLReset_<ContainerAllocator> const> ConstPtr;

}; // struct RLReset_

typedef ::rl_bridge::RLReset_<std::allocator<void> > RLReset;

typedef boost::shared_ptr< ::rl_bridge::RLReset > RLResetPtr;
typedef boost::shared_ptr< ::rl_bridge::RLReset const> RLResetConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rl_bridge::RLReset_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rl_bridge::RLReset_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rl_bridge::RLReset_<ContainerAllocator1> & lhs, const ::rl_bridge::RLReset_<ContainerAllocator2> & rhs)
{
  return lhs.reset == rhs.reset;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rl_bridge::RLReset_<ContainerAllocator1> & lhs, const ::rl_bridge::RLReset_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rl_bridge

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rl_bridge::RLReset_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rl_bridge::RLReset_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rl_bridge::RLReset_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rl_bridge::RLReset_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rl_bridge::RLReset_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rl_bridge::RLReset_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rl_bridge::RLReset_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ba4b0b221fb425ac5eaf73f71ae34971";
  }

  static const char* value(const ::rl_bridge::RLReset_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xba4b0b221fb425acULL;
  static const uint64_t static_value2 = 0x5eaf73f71ae34971ULL;
};

template<class ContainerAllocator>
struct DataType< ::rl_bridge::RLReset_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rl_bridge/RLReset";
  }

  static const char* value(const ::rl_bridge::RLReset_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rl_bridge::RLReset_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool reset\n"
;
  }

  static const char* value(const ::rl_bridge::RLReset_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rl_bridge::RLReset_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.reset);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RLReset_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rl_bridge::RLReset_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rl_bridge::RLReset_<ContainerAllocator>& v)
  {
    s << indent << "reset: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.reset);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RL_BRIDGE_MESSAGE_RLRESET_H
