// Generated by gencpp from file rl_bridge/RLReward.msg
// DO NOT EDIT!


#ifndef RL_BRIDGE_MESSAGE_RLREWARD_H
#define RL_BRIDGE_MESSAGE_RLREWARD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rl_bridge
{
template <class ContainerAllocator>
struct RLReward_
{
  typedef RLReward_<ContainerAllocator> Type;

  RLReward_()
    : reward(0.0)  {
    }
  RLReward_(const ContainerAllocator& _alloc)
    : reward(0.0)  {
  (void)_alloc;
    }



   typedef float _reward_type;
  _reward_type reward;





  typedef boost::shared_ptr< ::rl_bridge::RLReward_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rl_bridge::RLReward_<ContainerAllocator> const> ConstPtr;

}; // struct RLReward_

typedef ::rl_bridge::RLReward_<std::allocator<void> > RLReward;

typedef boost::shared_ptr< ::rl_bridge::RLReward > RLRewardPtr;
typedef boost::shared_ptr< ::rl_bridge::RLReward const> RLRewardConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rl_bridge::RLReward_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rl_bridge::RLReward_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rl_bridge::RLReward_<ContainerAllocator1> & lhs, const ::rl_bridge::RLReward_<ContainerAllocator2> & rhs)
{
  return lhs.reward == rhs.reward;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rl_bridge::RLReward_<ContainerAllocator1> & lhs, const ::rl_bridge::RLReward_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rl_bridge

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rl_bridge::RLReward_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rl_bridge::RLReward_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rl_bridge::RLReward_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rl_bridge::RLReward_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rl_bridge::RLReward_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rl_bridge::RLReward_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rl_bridge::RLReward_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1c5a2bbc277e822b80ec2fb352dd1efe";
  }

  static const char* value(const ::rl_bridge::RLReward_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1c5a2bbc277e822bULL;
  static const uint64_t static_value2 = 0x80ec2fb352dd1efeULL;
};

template<class ContainerAllocator>
struct DataType< ::rl_bridge::RLReward_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rl_bridge/RLReward";
  }

  static const char* value(const ::rl_bridge::RLReward_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rl_bridge::RLReward_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 reward\n"
;
  }

  static const char* value(const ::rl_bridge::RLReward_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rl_bridge::RLReward_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.reward);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RLReward_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rl_bridge::RLReward_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rl_bridge::RLReward_<ContainerAllocator>& v)
  {
    s << indent << "reward: ";
    Printer<float>::stream(s, indent + "  ", v.reward);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RL_BRIDGE_MESSAGE_RLREWARD_H
