(cl:defpackage nlp_drone_control-srv
  (:use )
  (:export
   "EXECUTEDRONEACTION"
   "<EXECUTEDRONEACTION-REQUEST>"
   "EXECUTEDRONEACTION-REQUEST"
   "<EXECUTEDRONEACTION-RESPONSE>"
   "EXECUTEDRONEACTION-RESPONSE"
  ))

