// Generated by gencpp from file vlm_service/CaptureImageResponse.msg
// DO NOT EDIT!


#ifndef VLM_SERVICE_MESSAGE_CAPTUREIMAGERESPONSE_H
#define VLM_SERVICE_MESSAGE_CAPTUREIMAGERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/Image.h>

namespace vlm_service
{
template <class ContainerAllocator>
struct CaptureImageResponse_
{
  typedef CaptureImageResponse_<ContainerAllocator> Type;

  CaptureImageResponse_()
    : success(false)
    , message()
    , file_path()
    , captured_image()  {
    }
  CaptureImageResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , message(_alloc)
    , file_path(_alloc)
    , captured_image(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  _message_type message;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _file_path_type;
  _file_path_type file_path;

   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _captured_image_type;
  _captured_image_type captured_image;





  typedef boost::shared_ptr< ::vlm_service::CaptureImageResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vlm_service::CaptureImageResponse_<ContainerAllocator> const> ConstPtr;

}; // struct CaptureImageResponse_

typedef ::vlm_service::CaptureImageResponse_<std::allocator<void> > CaptureImageResponse;

typedef boost::shared_ptr< ::vlm_service::CaptureImageResponse > CaptureImageResponsePtr;
typedef boost::shared_ptr< ::vlm_service::CaptureImageResponse const> CaptureImageResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vlm_service::CaptureImageResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vlm_service::CaptureImageResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vlm_service::CaptureImageResponse_<ContainerAllocator1> & lhs, const ::vlm_service::CaptureImageResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.message == rhs.message &&
    lhs.file_path == rhs.file_path &&
    lhs.captured_image == rhs.captured_image;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vlm_service::CaptureImageResponse_<ContainerAllocator1> & lhs, const ::vlm_service::CaptureImageResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vlm_service

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::vlm_service::CaptureImageResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vlm_service::CaptureImageResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vlm_service::CaptureImageResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vlm_service::CaptureImageResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vlm_service::CaptureImageResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vlm_service::CaptureImageResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vlm_service::CaptureImageResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "162e78e0b15db8f7728207b46fb9182f";
  }

  static const char* value(const ::vlm_service::CaptureImageResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x162e78e0b15db8f7ULL;
  static const uint64_t static_value2 = 0x728207b46fb9182fULL;
};

template<class ContainerAllocator>
struct DataType< ::vlm_service::CaptureImageResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vlm_service/CaptureImageResponse";
  }

  static const char* value(const ::vlm_service::CaptureImageResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vlm_service::CaptureImageResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Response: 返回操作结果和保存的完整路径\n"
"bool success\n"
"string message\n"
"string file_path # 新增：返回完整路径，方便客户端（如Unity）确认\n"
"sensor_msgs/Image captured_image  \n"
"\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/Image\n"
"# This message contains an uncompressed image\n"
"# (0, 0) is at top-left corner of image\n"
"#\n"
"\n"
"Header header        # Header timestamp should be acquisition time of image\n"
"                     # Header frame_id should be optical frame of camera\n"
"                     # origin of frame should be optical center of camera\n"
"                     # +x should point to the right in the image\n"
"                     # +y should point down in the image\n"
"                     # +z should point into to plane of the image\n"
"                     # If the frame_id here and the frame_id of the CameraInfo\n"
"                     # message associated with the image conflict\n"
"                     # the behavior is undefined\n"
"\n"
"uint32 height         # image height, that is, number of rows\n"
"uint32 width          # image width, that is, number of columns\n"
"\n"
"# The legal values for encoding are in file src/image_encodings.cpp\n"
"# If you want to standardize a new string format, join\n"
"# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n"
"\n"
"string encoding       # Encoding of pixels -- channel meaning, ordering, size\n"
"                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n"
"\n"
"uint8 is_bigendian    # is this data bigendian?\n"
"uint32 step           # Full row length in bytes\n"
"uint8[] data          # actual matrix data, size is (step * rows)\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::vlm_service::CaptureImageResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vlm_service::CaptureImageResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.message);
      stream.next(m.file_path);
      stream.next(m.captured_image);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CaptureImageResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vlm_service::CaptureImageResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vlm_service::CaptureImageResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.message);
    s << indent << "file_path: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.file_path);
    s << indent << "captured_image: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.captured_image);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VLM_SERVICE_MESSAGE_CAPTUREIMAGERESPONSE_H
