// Generated by gencpp from file vlm_service/CaptureImage.msg
// DO NOT EDIT!


#ifndef VLM_SERVICE_MESSAGE_CAPTUREIMAGE_H
#define VLM_SERVICE_MESSAGE_CAPTUREIMAGE_H

#include <ros/service_traits.h>


#include <vlm_service/CaptureImageRequest.h>
#include <vlm_service/CaptureImageResponse.h>


namespace vlm_service
{

struct CaptureImage
{

typedef CaptureImageRequest Request;
typedef CaptureImageResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CaptureImage
} // namespace vlm_service


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::vlm_service::CaptureImage > {
  static const char* value()
  {
    return "4c904431fc96748b50b74feb53b9fa12";
  }

  static const char* value(const ::vlm_service::CaptureImage&) { return value(); }
};

template<>
struct DataType< ::vlm_service::CaptureImage > {
  static const char* value()
  {
    return "vlm_service/CaptureImage";
  }

  static const char* value(const ::vlm_service::CaptureImage&) { return value(); }
};


// service_traits::MD5Sum< ::vlm_service::CaptureImageRequest> should match
// service_traits::MD5Sum< ::vlm_service::CaptureImage >
template<>
struct MD5Sum< ::vlm_service::CaptureImageRequest>
{
  static const char* value()
  {
    return MD5Sum< ::vlm_service::CaptureImage >::value();
  }
  static const char* value(const ::vlm_service::CaptureImageRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::vlm_service::CaptureImageRequest> should match
// service_traits::DataType< ::vlm_service::CaptureImage >
template<>
struct DataType< ::vlm_service::CaptureImageRequest>
{
  static const char* value()
  {
    return DataType< ::vlm_service::CaptureImage >::value();
  }
  static const char* value(const ::vlm_service::CaptureImageRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::vlm_service::CaptureImageResponse> should match
// service_traits::MD5Sum< ::vlm_service::CaptureImage >
template<>
struct MD5Sum< ::vlm_service::CaptureImageResponse>
{
  static const char* value()
  {
    return MD5Sum< ::vlm_service::CaptureImage >::value();
  }
  static const char* value(const ::vlm_service::CaptureImageResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::vlm_service::CaptureImageResponse> should match
// service_traits::DataType< ::vlm_service::CaptureImage >
template<>
struct DataType< ::vlm_service::CaptureImageResponse>
{
  static const char* value()
  {
    return DataType< ::vlm_service::CaptureImage >::value();
  }
  static const char* value(const ::vlm_service::CaptureImageResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VLM_SERVICE_MESSAGE_CAPTUREIMAGE_H
