// Generated by gencpp from file vlm_service/DescribeScene.msg
// DO NOT EDIT!


#ifndef VLM_SERVICE_MESSAGE_DESCRIBESCENE_H
#define VLM_SERVICE_MESSAGE_DESCRIBESCENE_H

#include <ros/service_traits.h>


#include <vlm_service/DescribeSceneRequest.h>
#include <vlm_service/DescribeSceneResponse.h>


namespace vlm_service
{

struct DescribeScene
{

typedef DescribeSceneRequest Request;
typedef DescribeSceneResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DescribeScene
} // namespace vlm_service


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::vlm_service::DescribeScene > {
  static const char* value()
  {
    return "edba9cc6ddda26cb7fba80817828a2a9";
  }

  static const char* value(const ::vlm_service::DescribeScene&) { return value(); }
};

template<>
struct DataType< ::vlm_service::DescribeScene > {
  static const char* value()
  {
    return "vlm_service/DescribeScene";
  }

  static const char* value(const ::vlm_service::DescribeScene&) { return value(); }
};


// service_traits::MD5Sum< ::vlm_service::DescribeSceneRequest> should match
// service_traits::MD5Sum< ::vlm_service::DescribeScene >
template<>
struct MD5Sum< ::vlm_service::DescribeSceneRequest>
{
  static const char* value()
  {
    return MD5Sum< ::vlm_service::DescribeScene >::value();
  }
  static const char* value(const ::vlm_service::DescribeSceneRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::vlm_service::DescribeSceneRequest> should match
// service_traits::DataType< ::vlm_service::DescribeScene >
template<>
struct DataType< ::vlm_service::DescribeSceneRequest>
{
  static const char* value()
  {
    return DataType< ::vlm_service::DescribeScene >::value();
  }
  static const char* value(const ::vlm_service::DescribeSceneRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::vlm_service::DescribeSceneResponse> should match
// service_traits::MD5Sum< ::vlm_service::DescribeScene >
template<>
struct MD5Sum< ::vlm_service::DescribeSceneResponse>
{
  static const char* value()
  {
    return MD5Sum< ::vlm_service::DescribeScene >::value();
  }
  static const char* value(const ::vlm_service::DescribeSceneResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::vlm_service::DescribeSceneResponse> should match
// service_traits::DataType< ::vlm_service::DescribeScene >
template<>
struct DataType< ::vlm_service::DescribeSceneResponse>
{
  static const char* value()
  {
    return DataType< ::vlm_service::DescribeScene >::value();
  }
  static const char* value(const ::vlm_service::DescribeSceneResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VLM_SERVICE_MESSAGE_DESCRIBESCENE_H
