(cl:defpackage fleet_manager-srv
  (:use )
  (:export
   "INJECTTASKS"
   "<INJECTTASKS-REQUEST>"
   "INJECTTASKS-REQUEST"
   "<INJECTTASKS-RESPONSE>"
   "INJECTTASKS-RESPONSE"
   "QUERYFLEETANDTASKS"
   "<QUERYFLEETANDTASKS-REQUEST>"
   "QUERYFLEETANDTASKS-REQUEST"
   "<QUERYFLEETANDTASKS-RESPONSE>"
   "QUERYFLEETANDTASKS-RESPONSE"
  ))

