// Generated by gencpp from file custom_msgs/DoneInfo.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_DONEINFO_H
#define CUSTOM_MSGS_MESSAGE_DONEINFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace custom_msgs
{
template <class ContainerAllocator>
struct DoneInfo_
{
  typedef DoneInfo_<ContainerAllocator> Type;

  DoneInfo_()
    : is_done(false)
    , is_success(false)
    , reason()  {
    }
  DoneInfo_(const ContainerAllocator& _alloc)
    : is_done(false)
    , is_success(false)
    , reason(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _is_done_type;
  _is_done_type is_done;

   typedef uint8_t _is_success_type;
  _is_success_type is_success;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _reason_type;
  _reason_type reason;





  typedef boost::shared_ptr< ::custom_msgs::DoneInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msgs::DoneInfo_<ContainerAllocator> const> ConstPtr;

}; // struct DoneInfo_

typedef ::custom_msgs::DoneInfo_<std::allocator<void> > DoneInfo;

typedef boost::shared_ptr< ::custom_msgs::DoneInfo > DoneInfoPtr;
typedef boost::shared_ptr< ::custom_msgs::DoneInfo const> DoneInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msgs::DoneInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msgs::DoneInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::custom_msgs::DoneInfo_<ContainerAllocator1> & lhs, const ::custom_msgs::DoneInfo_<ContainerAllocator2> & rhs)
{
  return lhs.is_done == rhs.is_done &&
    lhs.is_success == rhs.is_success &&
    lhs.reason == rhs.reason;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::custom_msgs::DoneInfo_<ContainerAllocator1> & lhs, const ::custom_msgs::DoneInfo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace custom_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::DoneInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::DoneInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::DoneInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::DoneInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::DoneInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::DoneInfo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msgs::DoneInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f554d70bf7374158f003bce0d316e6fd";
  }

  static const char* value(const ::custom_msgs::DoneInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf554d70bf7374158ULL;
  static const uint64_t static_value2 = 0xf003bce0d316e6fdULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msgs::DoneInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msgs/DoneInfo";
  }

  static const char* value(const ::custom_msgs::DoneInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msgs::DoneInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool is_done\n"
"bool is_success\n"
"string reason\n"
;
  }

  static const char* value(const ::custom_msgs::DoneInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msgs::DoneInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.is_done);
      stream.next(m.is_success);
      stream.next(m.reason);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DoneInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msgs::DoneInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msgs::DoneInfo_<ContainerAllocator>& v)
  {
    s << indent << "is_done: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_done);
    s << indent << "is_success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_success);
    s << indent << "reason: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.reason);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_DONEINFO_H
