// Generated by gencpp from file custom_msgs/ResetEpisodeResponse.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_RESETEPISODERESPONSE_H
#define CUSTOM_MSGS_MESSAGE_RESETEPISODERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Point.h>

namespace custom_msgs
{
template <class ContainerAllocator>
struct ResetEpisodeResponse_
{
  typedef ResetEpisodeResponse_<ContainerAllocator> Type;

  ResetEpisodeResponse_()
    : success(false)
    , message()
    , start_pose()
    , goal_position()  {
    }
  ResetEpisodeResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , message(_alloc)
    , start_pose(_alloc)
    , goal_position(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  _message_type message;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _start_pose_type;
  _start_pose_type start_pose;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _goal_position_type;
  _goal_position_type goal_position;





  typedef boost::shared_ptr< ::custom_msgs::ResetEpisodeResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msgs::ResetEpisodeResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ResetEpisodeResponse_

typedef ::custom_msgs::ResetEpisodeResponse_<std::allocator<void> > ResetEpisodeResponse;

typedef boost::shared_ptr< ::custom_msgs::ResetEpisodeResponse > ResetEpisodeResponsePtr;
typedef boost::shared_ptr< ::custom_msgs::ResetEpisodeResponse const> ResetEpisodeResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msgs::ResetEpisodeResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msgs::ResetEpisodeResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::custom_msgs::ResetEpisodeResponse_<ContainerAllocator1> & lhs, const ::custom_msgs::ResetEpisodeResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.message == rhs.message &&
    lhs.start_pose == rhs.start_pose &&
    lhs.goal_position == rhs.goal_position;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::custom_msgs::ResetEpisodeResponse_<ContainerAllocator1> & lhs, const ::custom_msgs::ResetEpisodeResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace custom_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::ResetEpisodeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::ResetEpisodeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::ResetEpisodeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::ResetEpisodeResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::ResetEpisodeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::ResetEpisodeResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msgs::ResetEpisodeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e566690f9c9e0029132e05fa58e0f836";
  }

  static const char* value(const ::custom_msgs::ResetEpisodeResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe566690f9c9e0029ULL;
  static const uint64_t static_value2 = 0x132e05fa58e0f836ULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msgs::ResetEpisodeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msgs/ResetEpisodeResponse";
  }

  static const char* value(const ::custom_msgs::ResetEpisodeResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msgs::ResetEpisodeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"# --- Response ---\n"
"# Unity找到的安全点将在这里返回\n"
"bool success          # 标记重置是否成功\n"
"string message        # 附带信息 (例如，失败原因)\n"
"geometry_msgs/Pose start_pose\n"
"geometry_msgs/Point goal_position\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::custom_msgs::ResetEpisodeResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msgs::ResetEpisodeResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.message);
      stream.next(m.start_pose);
      stream.next(m.goal_position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ResetEpisodeResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msgs::ResetEpisodeResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msgs::ResetEpisodeResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.message);
    s << indent << "start_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.start_pose);
    s << indent << "goal_position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_position);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_RESETEPISODERESPONSE_H
