// Generated by gencpp from file custom_msgs/UpdateCurriculumResponse.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_UPDATECURRICULUMRESPONSE_H
#define CUSTOM_MSGS_MESSAGE_UPDATECURRICULUMRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace custom_msgs
{
template <class ContainerAllocator>
struct UpdateCurriculumResponse_
{
  typedef UpdateCurriculumResponse_<ContainerAllocator> Type;

  UpdateCurriculumResponse_()
    : success(false)  {
    }
  UpdateCurriculumResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::custom_msgs::UpdateCurriculumResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msgs::UpdateCurriculumResponse_<ContainerAllocator> const> ConstPtr;

}; // struct UpdateCurriculumResponse_

typedef ::custom_msgs::UpdateCurriculumResponse_<std::allocator<void> > UpdateCurriculumResponse;

typedef boost::shared_ptr< ::custom_msgs::UpdateCurriculumResponse > UpdateCurriculumResponsePtr;
typedef boost::shared_ptr< ::custom_msgs::UpdateCurriculumResponse const> UpdateCurriculumResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msgs::UpdateCurriculumResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msgs::UpdateCurriculumResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::custom_msgs::UpdateCurriculumResponse_<ContainerAllocator1> & lhs, const ::custom_msgs::UpdateCurriculumResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::custom_msgs::UpdateCurriculumResponse_<ContainerAllocator1> & lhs, const ::custom_msgs::UpdateCurriculumResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace custom_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::UpdateCurriculumResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::UpdateCurriculumResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::UpdateCurriculumResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::UpdateCurriculumResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::UpdateCurriculumResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::UpdateCurriculumResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msgs::UpdateCurriculumResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::custom_msgs::UpdateCurriculumResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msgs::UpdateCurriculumResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msgs/UpdateCurriculumResponse";
  }

  static const char* value(const ::custom_msgs::UpdateCurriculumResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msgs::UpdateCurriculumResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"\n"
;
  }

  static const char* value(const ::custom_msgs::UpdateCurriculumResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msgs::UpdateCurriculumResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct UpdateCurriculumResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msgs::UpdateCurriculumResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msgs::UpdateCurriculumResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_UPDATECURRICULUMRESPONSE_H
