(cl:defpackage vlm_service-srv
  (:use )
  (:export
   "CAPTUREIMAGE"
   "<CAPTUREIMAGE-REQUEST>"
   "CAPTUREIMAGE-REQUEST"
   "<CAPTUREIMAGE-RESPONSE>"
   "CAPTUREIMAGE-RESPONSE"
   "DESCRIBESCENE"
   "<DESCRIBESCENE-REQUEST>"
   "DESCRIBESCENE-REQUEST"
   "<DESCRIBESCENE-RESPONSE>"
   "DESCRIBESCENE-RESPONSE"
  ))

