# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from fleet_manager/DroneStatus.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class DroneStatus(genpy.Message):
  _md5sum = "4399a33682bd42bcbd894637e74a998e"
  _type = "fleet_manager/DroneStatus"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# [修改] 在消息定义中添加常量
# Drone Status Constants
uint8 UNKNOWN=0
uint8 ACTIVE=1
uint8 NEEDS_BACKUP=2
uint8 OFFLINE=3

# Message Fields
string drone_id
uint8 status
int32 last_completed_task_index
geometry_msgs/Pose last_known_pose

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w
"""
  # Pseudo-constants
  UNKNOWN = 0
  ACTIVE = 1
  NEEDS_BACKUP = 2
  OFFLINE = 3

  __slots__ = ['drone_id','status','last_completed_task_index','last_known_pose']
  _slot_types = ['string','uint8','int32','geometry_msgs/Pose']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       drone_id,status,last_completed_task_index,last_known_pose

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(DroneStatus, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.drone_id is None:
        self.drone_id = ''
      if self.status is None:
        self.status = 0
      if self.last_completed_task_index is None:
        self.last_completed_task_index = 0
      if self.last_known_pose is None:
        self.last_known_pose = geometry_msgs.msg.Pose()
    else:
      self.drone_id = ''
      self.status = 0
      self.last_completed_task_index = 0
      self.last_known_pose = geometry_msgs.msg.Pose()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.drone_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_Bi7d().pack(_x.status, _x.last_completed_task_index, _x.last_known_pose.position.x, _x.last_known_pose.position.y, _x.last_known_pose.position.z, _x.last_known_pose.orientation.x, _x.last_known_pose.orientation.y, _x.last_known_pose.orientation.z, _x.last_known_pose.orientation.w))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.last_known_pose is None:
        self.last_known_pose = geometry_msgs.msg.Pose()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.drone_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.drone_id = str[start:end]
      _x = self
      start = end
      end += 61
      (_x.status, _x.last_completed_task_index, _x.last_known_pose.position.x, _x.last_known_pose.position.y, _x.last_known_pose.position.z, _x.last_known_pose.orientation.x, _x.last_known_pose.orientation.y, _x.last_known_pose.orientation.z, _x.last_known_pose.orientation.w,) = _get_struct_Bi7d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.drone_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_Bi7d().pack(_x.status, _x.last_completed_task_index, _x.last_known_pose.position.x, _x.last_known_pose.position.y, _x.last_known_pose.position.z, _x.last_known_pose.orientation.x, _x.last_known_pose.orientation.y, _x.last_known_pose.orientation.z, _x.last_known_pose.orientation.w))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.last_known_pose is None:
        self.last_known_pose = geometry_msgs.msg.Pose()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.drone_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.drone_id = str[start:end]
      _x = self
      start = end
      end += 61
      (_x.status, _x.last_completed_task_index, _x.last_known_pose.position.x, _x.last_known_pose.position.y, _x.last_known_pose.position.z, _x.last_known_pose.orientation.x, _x.last_known_pose.orientation.y, _x.last_known_pose.orientation.z, _x.last_known_pose.orientation.w,) = _get_struct_Bi7d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_Bi7d = None
def _get_struct_Bi7d():
    global _struct_Bi7d
    if _struct_Bi7d is None:
        _struct_Bi7d = struct.Struct("<Bi7d")
    return _struct_Bi7d
