// Generated by gencpp from file uav_scheduler/ComputeAssignment.msg
// DO NOT EDIT!


#ifndef UAV_SCHEDULER_MESSAGE_COMPUTEASSIGNMENT_H
#define UAV_SCHEDULER_MESSAGE_COMPUTEASSIGNMENT_H

#include <ros/service_traits.h>


#include <uav_scheduler/ComputeAssignmentRequest.h>
#include <uav_scheduler/ComputeAssignmentResponse.h>


namespace uav_scheduler
{

struct ComputeAssignment
{

typedef ComputeAssignmentRequest Request;
typedef ComputeAssignmentResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ComputeAssignment
} // namespace uav_scheduler


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::uav_scheduler::ComputeAssignment > {
  static const char* value()
  {
    return "97370e26157faf720c13585eba94765b";
  }

  static const char* value(const ::uav_scheduler::ComputeAssignment&) { return value(); }
};

template<>
struct DataType< ::uav_scheduler::ComputeAssignment > {
  static const char* value()
  {
    return "uav_scheduler/ComputeAssignment";
  }

  static const char* value(const ::uav_scheduler::ComputeAssignment&) { return value(); }
};


// service_traits::MD5Sum< ::uav_scheduler::ComputeAssignmentRequest> should match
// service_traits::MD5Sum< ::uav_scheduler::ComputeAssignment >
template<>
struct MD5Sum< ::uav_scheduler::ComputeAssignmentRequest>
{
  static const char* value()
  {
    return MD5Sum< ::uav_scheduler::ComputeAssignment >::value();
  }
  static const char* value(const ::uav_scheduler::ComputeAssignmentRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::uav_scheduler::ComputeAssignmentRequest> should match
// service_traits::DataType< ::uav_scheduler::ComputeAssignment >
template<>
struct DataType< ::uav_scheduler::ComputeAssignmentRequest>
{
  static const char* value()
  {
    return DataType< ::uav_scheduler::ComputeAssignment >::value();
  }
  static const char* value(const ::uav_scheduler::ComputeAssignmentRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::uav_scheduler::ComputeAssignmentResponse> should match
// service_traits::MD5Sum< ::uav_scheduler::ComputeAssignment >
template<>
struct MD5Sum< ::uav_scheduler::ComputeAssignmentResponse>
{
  static const char* value()
  {
    return MD5Sum< ::uav_scheduler::ComputeAssignment >::value();
  }
  static const char* value(const ::uav_scheduler::ComputeAssignmentResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::uav_scheduler::ComputeAssignmentResponse> should match
// service_traits::DataType< ::uav_scheduler::ComputeAssignment >
template<>
struct DataType< ::uav_scheduler::ComputeAssignmentResponse>
{
  static const char* value()
  {
    return DataType< ::uav_scheduler::ComputeAssignment >::value();
  }
  static const char* value(const ::uav_scheduler::ComputeAssignmentResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UAV_SCHEDULER_MESSAGE_COMPUTEASSIGNMENT_H
