// Generated by gencpp from file uav_scheduler/ComputeAssignmentResponse.msg
// DO NOT EDIT!


#ifndef UAV_SCHEDULER_MESSAGE_COMPUTEASSIGNMENTRESPONSE_H
#define UAV_SCHEDULER_MESSAGE_COMPUTEASSIGNMENTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace uav_scheduler
{
template <class ContainerAllocator>
struct ComputeAssignmentResponse_
{
  typedef ComputeAssignmentResponse_<ContainerAllocator> Type;

  ComputeAssignmentResponse_()
    : assignments()
    , plan_text()  {
    }
  ComputeAssignmentResponse_(const ContainerAllocator& _alloc)
    : assignments(_alloc)
    , plan_text(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _assignments_type;
  _assignments_type assignments;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _plan_text_type;
  _plan_text_type plan_text;





  typedef boost::shared_ptr< ::uav_scheduler::ComputeAssignmentResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uav_scheduler::ComputeAssignmentResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ComputeAssignmentResponse_

typedef ::uav_scheduler::ComputeAssignmentResponse_<std::allocator<void> > ComputeAssignmentResponse;

typedef boost::shared_ptr< ::uav_scheduler::ComputeAssignmentResponse > ComputeAssignmentResponsePtr;
typedef boost::shared_ptr< ::uav_scheduler::ComputeAssignmentResponse const> ComputeAssignmentResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uav_scheduler::ComputeAssignmentResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uav_scheduler::ComputeAssignmentResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::uav_scheduler::ComputeAssignmentResponse_<ContainerAllocator1> & lhs, const ::uav_scheduler::ComputeAssignmentResponse_<ContainerAllocator2> & rhs)
{
  return lhs.assignments == rhs.assignments &&
    lhs.plan_text == rhs.plan_text;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::uav_scheduler::ComputeAssignmentResponse_<ContainerAllocator1> & lhs, const ::uav_scheduler::ComputeAssignmentResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace uav_scheduler

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::uav_scheduler::ComputeAssignmentResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uav_scheduler::ComputeAssignmentResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uav_scheduler::ComputeAssignmentResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uav_scheduler::ComputeAssignmentResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uav_scheduler::ComputeAssignmentResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uav_scheduler::ComputeAssignmentResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uav_scheduler::ComputeAssignmentResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0e46fb8d1fa4812f772ec00b1475a3a6";
  }

  static const char* value(const ::uav_scheduler::ComputeAssignmentResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0e46fb8d1fa4812fULL;
  static const uint64_t static_value2 = 0x772ec00b1475a3a6ULL;
};

template<class ContainerAllocator>
struct DataType< ::uav_scheduler::ComputeAssignmentResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uav_scheduler/ComputeAssignmentResponse";
  }

  static const char* value(const ::uav_scheduler::ComputeAssignmentResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uav_scheduler::ComputeAssignmentResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 输出\n"
"string[] assignments          # 匹配结果，例如 V_UAV_0->House1\n"
"string plan_text              # 任务动作文本\n"
"\n"
"\n"
;
  }

  static const char* value(const ::uav_scheduler::ComputeAssignmentResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uav_scheduler::ComputeAssignmentResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.assignments);
      stream.next(m.plan_text);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ComputeAssignmentResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uav_scheduler::ComputeAssignmentResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::uav_scheduler::ComputeAssignmentResponse_<ContainerAllocator>& v)
  {
    s << indent << "assignments[]" << std::endl;
    for (size_t i = 0; i < v.assignments.size(); ++i)
    {
      s << indent << "  assignments[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.assignments[i]);
    }
    s << indent << "plan_text: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.plan_text);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UAV_SCHEDULER_MESSAGE_COMPUTEASSIGNMENTRESPONSE_H
