// Generated by gencpp from file uav_scheduler/ComputeAssignmentRequest.msg
// DO NOT EDIT!


#ifndef UAV_SCHEDULER_MESSAGE_COMPUTEASSIGNMENTREQUEST_H
#define UAV_SCHEDULER_MESSAGE_COMPUTEASSIGNMENTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace uav_scheduler
{
template <class ContainerAllocator>
struct ComputeAssignmentRequest_
{
  typedef ComputeAssignmentRequest_<ContainerAllocator> Type;

  ComputeAssignmentRequest_()
    : algorithm()
    , drones()
    , pois()  {
    }
  ComputeAssignmentRequest_(const ContainerAllocator& _alloc)
    : algorithm(_alloc)
    , drones(_alloc)
    , pois(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _algorithm_type;
  _algorithm_type algorithm;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _drones_type;
  _drones_type drones;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _pois_type;
  _pois_type pois;





  typedef boost::shared_ptr< ::uav_scheduler::ComputeAssignmentRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uav_scheduler::ComputeAssignmentRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ComputeAssignmentRequest_

typedef ::uav_scheduler::ComputeAssignmentRequest_<std::allocator<void> > ComputeAssignmentRequest;

typedef boost::shared_ptr< ::uav_scheduler::ComputeAssignmentRequest > ComputeAssignmentRequestPtr;
typedef boost::shared_ptr< ::uav_scheduler::ComputeAssignmentRequest const> ComputeAssignmentRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uav_scheduler::ComputeAssignmentRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uav_scheduler::ComputeAssignmentRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::uav_scheduler::ComputeAssignmentRequest_<ContainerAllocator1> & lhs, const ::uav_scheduler::ComputeAssignmentRequest_<ContainerAllocator2> & rhs)
{
  return lhs.algorithm == rhs.algorithm &&
    lhs.drones == rhs.drones &&
    lhs.pois == rhs.pois;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::uav_scheduler::ComputeAssignmentRequest_<ContainerAllocator1> & lhs, const ::uav_scheduler::ComputeAssignmentRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace uav_scheduler

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::uav_scheduler::ComputeAssignmentRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uav_scheduler::ComputeAssignmentRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uav_scheduler::ComputeAssignmentRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uav_scheduler::ComputeAssignmentRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uav_scheduler::ComputeAssignmentRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uav_scheduler::ComputeAssignmentRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uav_scheduler::ComputeAssignmentRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c8cce96eb27806832f78ff0d0d73a350";
  }

  static const char* value(const ::uav_scheduler::ComputeAssignmentRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc8cce96eb2780683ULL;
  static const uint64_t static_value2 = 0x2f78ff0d0d73a350ULL;
};

template<class ContainerAllocator>
struct DataType< ::uav_scheduler::ComputeAssignmentRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uav_scheduler/ComputeAssignmentRequest";
  }

  static const char* value(const ::uav_scheduler::ComputeAssignmentRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uav_scheduler::ComputeAssignmentRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 输入\n"
"string algorithm              # \"hungarian\", \"auction\", \"genetic\", \"distributed_auction\"\n"
"string[] drones\n"
"string[] pois\n"
;
  }

  static const char* value(const ::uav_scheduler::ComputeAssignmentRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uav_scheduler::ComputeAssignmentRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.algorithm);
      stream.next(m.drones);
      stream.next(m.pois);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ComputeAssignmentRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uav_scheduler::ComputeAssignmentRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::uav_scheduler::ComputeAssignmentRequest_<ContainerAllocator>& v)
  {
    s << indent << "algorithm: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.algorithm);
    s << indent << "drones[]" << std::endl;
    for (size_t i = 0; i < v.drones.size(); ++i)
    {
      s << indent << "  drones[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.drones[i]);
    }
    s << indent << "pois[]" << std::endl;
    for (size_t i = 0; i < v.pois.size(); ++i)
    {
      s << indent << "  pois[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.pois[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // UAV_SCHEDULER_MESSAGE_COMPUTEASSIGNMENTREQUEST_H
