// Generated by gencpp from file nlp_drone_control/ExecuteDroneActionRequest.msg
// DO NOT EDIT!


#ifndef NLP_DRONE_CONTROL_MESSAGE_EXECUTEDRONEACTIONREQUEST_H
#define NLP_DRONE_CONTROL_MESSAGE_EXECUTEDRONEACTIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace nlp_drone_control
{
template <class ContainerAllocator>
struct ExecuteDroneActionRequest_
{
  typedef ExecuteDroneActionRequest_<ContainerAllocator> Type;

  ExecuteDroneActionRequest_()
    : action_type()
    , params_json()  {
    }
  ExecuteDroneActionRequest_(const ContainerAllocator& _alloc)
    : action_type(_alloc)
    , params_json(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _action_type_type;
  _action_type_type action_type;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _params_json_type;
  _params_json_type params_json;





  typedef boost::shared_ptr< ::nlp_drone_control::ExecuteDroneActionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nlp_drone_control::ExecuteDroneActionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ExecuteDroneActionRequest_

typedef ::nlp_drone_control::ExecuteDroneActionRequest_<std::allocator<void> > ExecuteDroneActionRequest;

typedef boost::shared_ptr< ::nlp_drone_control::ExecuteDroneActionRequest > ExecuteDroneActionRequestPtr;
typedef boost::shared_ptr< ::nlp_drone_control::ExecuteDroneActionRequest const> ExecuteDroneActionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nlp_drone_control::ExecuteDroneActionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nlp_drone_control::ExecuteDroneActionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::nlp_drone_control::ExecuteDroneActionRequest_<ContainerAllocator1> & lhs, const ::nlp_drone_control::ExecuteDroneActionRequest_<ContainerAllocator2> & rhs)
{
  return lhs.action_type == rhs.action_type &&
    lhs.params_json == rhs.params_json;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::nlp_drone_control::ExecuteDroneActionRequest_<ContainerAllocator1> & lhs, const ::nlp_drone_control::ExecuteDroneActionRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace nlp_drone_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::nlp_drone_control::ExecuteDroneActionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nlp_drone_control::ExecuteDroneActionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nlp_drone_control::ExecuteDroneActionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nlp_drone_control::ExecuteDroneActionRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nlp_drone_control::ExecuteDroneActionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nlp_drone_control::ExecuteDroneActionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nlp_drone_control::ExecuteDroneActionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2601bc24fd4babc166c150f2f3f63219";
  }

  static const char* value(const ::nlp_drone_control::ExecuteDroneActionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2601bc24fd4babc1ULL;
  static const uint64_t static_value2 = 0x66c150f2f3f63219ULL;
};

template<class ContainerAllocator>
struct DataType< ::nlp_drone_control::ExecuteDroneActionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nlp_drone_control/ExecuteDroneActionRequest";
  }

  static const char* value(const ::nlp_drone_control::ExecuteDroneActionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nlp_drone_control::ExecuteDroneActionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# --- Request ---\n"
"# 动作的类型，例如 \"adjust_camera\", \"rotate_360\", \"hover_and_monitor\"\n"
"string action_type\n"
"\n"
"# (可选) 动作的参数，我们可以用一个JSON字符串来灵活地传递\n"
"# 例如：对于adjust_camera, params可以是 \"{\\\"pitch_angle\\\": -90.0}\"\n"
"# 对于hover_and_monitor, params可以是 \"{\\\"duration_seconds\\\": 5.0}\"\n"
"string params_json\n"
"\n"
;
  }

  static const char* value(const ::nlp_drone_control::ExecuteDroneActionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nlp_drone_control::ExecuteDroneActionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.action_type);
      stream.next(m.params_json);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ExecuteDroneActionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nlp_drone_control::ExecuteDroneActionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nlp_drone_control::ExecuteDroneActionRequest_<ContainerAllocator>& v)
  {
    s << indent << "action_type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.action_type);
    s << indent << "params_json: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.params_json);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NLP_DRONE_CONTROL_MESSAGE_EXECUTEDRONEACTIONREQUEST_H
